// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: ateom.proto

package ateompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotScope int32

const (
	// Not valid option; should never happen.
	SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED SnapshotScope = 0
	// Capture process memory plus the full filesystem delta on top of the OCI
	// image (including any attached DurableDir volumes).
	SnapshotScope_SNAPSHOT_SCOPE_FULL SnapshotScope = 1
	// Capture only the contents of attached volumes that support snapshots
	// (currently DurableDir-typed volumes). Memory and the rest of rootfs are
	// excluded.
	SnapshotScope_SNAPSHOT_SCOPE_DATA SnapshotScope = 2
	// Restore-only: restore the ActorTemplate's golden snapshot's guest state
	// (memory + full filesystem delta) combined with the snapshot's durable
	// data. Never valid for CheckpointWorkload — snapshots only ever capture
	// FULL or DATA; the control plane selects this scope at restore per the
	// template's onResume configuration.
	SnapshotScope_SNAPSHOT_SCOPE_DATA_ON_GOLDEN SnapshotScope = 3
)

// Enum value maps for SnapshotScope.
var (
	SnapshotScope_name = map[int32]string{
		0: "SNAPSHOT_SCOPE_UNSPECIFIED",
		1: "SNAPSHOT_SCOPE_FULL",
		2: "SNAPSHOT_SCOPE_DATA",
		3: "SNAPSHOT_SCOPE_DATA_ON_GOLDEN",
	}
	SnapshotScope_value = map[string]int32{
		"SNAPSHOT_SCOPE_UNSPECIFIED":    0,
		"SNAPSHOT_SCOPE_FULL":           1,
		"SNAPSHOT_SCOPE_DATA":           2,
		"SNAPSHOT_SCOPE_DATA_ON_GOLDEN": 3,
	}
)

func (x SnapshotScope) Enum() *SnapshotScope {
	p := new(SnapshotScope)
	*p = x
	return p
}

func (x SnapshotScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotScope) Descriptor() protoreflect.EnumDescriptor {
	return file_ateom_proto_enumTypes[0].Descriptor()
}

func (SnapshotScope) Type() protoreflect.EnumType {
	return &file_ateom_proto_enumTypes[0]
}

func (x SnapshotScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotScope.Descriptor instead.
func (SnapshotScope) EnumDescriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{0}
}

type RunWorkloadRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Atespace  string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid  string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	// Actor resource version observed by ate-api when assigning this worker.
	ActorVersion           int64         `protobuf:"varint,9,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`
	ActorTemplateNamespace string        `protobuf:"bytes,4,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string        `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath              string        `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                   *WorkloadSpec `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// runtime_asset_paths maps a runtime asset name (e.g. "cloud-hypervisor",
	// "virtiofsd", "kata-kernel", "kata-image", "kata-config")
	// to the local on-disk path atelet fetched it to (content-addressed, like
	// runsc_path). Empty for the gVisor runtime, which uses runsc_path.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,8,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Remote egress gateway selected for this activation. When absent, actor
	// traffic uses direct egress instead of being redirected through atunnel.
	EgressGatewayAddress *string `protobuf:"bytes,10,opt,name=egress_gateway_address,json=egressGatewayAddress,proto3,oneof" json:"egress_gateway_address,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RunWorkloadRequest) Reset() {
	*x = RunWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadRequest) ProtoMessage() {}

func (x *RunWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RunWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{0}
}

func (x *RunWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorVersion() int64 {
	if x != nil {
		return x.ActorVersion
	}
	return 0
}

func (x *RunWorkloadRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RunWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *RunWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RunWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *RunWorkloadRequest) GetEgressGatewayAddress() string {
	if x != nil && x.EgressGatewayAddress != nil {
		return *x.EgressGatewayAddress
	}
	return ""
}

// WorkloadSpec parallels Pod, but with far fewer configurable fields.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_ateom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Readyz *Readyz                `protobuf:"bytes,2,opt,name=readyz,proto3" json:"readyz,omitempty"`
	// durable_dir_volume_mounts are the durable-dir volumes this container
	// mounts, if any.
	DurableDirVolumeMounts []*DurableDirVolumeMount `protobuf:"bytes,4,rep,name=durable_dir_volume_mounts,json=durableDirVolumeMounts,proto3" json:"durable_dir_volume_mounts,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_ateom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetReadyz() *Readyz {
	if x != nil {
		return x.Readyz
	}
	return nil
}

func (x *Container) GetDurableDirVolumeMounts() []*DurableDirVolumeMount {
	if x != nil {
		return x.DurableDirVolumeMounts
	}
	return nil
}

// DurableDirVolumeMount is one durable-dir volume mounted into a container.
type DurableDirVolumeMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_name is the name the ActorTemplate gave the volume. It selects the
	// per-volume directory atelet prepared for the actor on the host.
	VolumeName string `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// mount_path is where the container sees the volume.
	MountPath     string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableDirVolumeMount) Reset() {
	*x = DurableDirVolumeMount{}
	mi := &file_ateom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableDirVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableDirVolumeMount) ProtoMessage() {}

func (x *DurableDirVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableDirVolumeMount.ProtoReflect.Descriptor instead.
func (*DurableDirVolumeMount) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{3}
}

func (x *DurableDirVolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *DurableDirVolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

// Readyz describes how to check that a container is ready to serve.
// Only HTTP is supported today.
type Readyz struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HttpGet *HTTPGetAction         `protobuf:"bytes,1,opt,name=http_get,json=httpGet,proto3" json:"http_get,omitempty"`
	// How long to keep polling before giving up and failing the actor start.
	// Zero means the ateom's default.
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Readyz) Reset() {
	*x = Readyz{}
	mi := &file_ateom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Readyz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Readyz) ProtoMessage() {}

func (x *Readyz) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Readyz.ProtoReflect.Descriptor instead.
func (*Readyz) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{4}
}

func (x *Readyz) GetHttpGet() *HTTPGetAction {
	if x != nil {
		return x.HttpGet
	}
	return nil
}

func (x *Readyz) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// HTTPGetAction performs an HTTP GET against the container.
type HTTPGetAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to access on the HTTP server. Empty means "/readyz".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// TCP port to connect to (1..65535).
	Port          int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPGetAction) Reset() {
	*x = HTTPGetAction{}
	mi := &file_ateom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetAction) ProtoMessage() {}

func (x *HTTPGetAction) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetAction.ProtoReflect.Descriptor instead.
func (*HTTPGetAction) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPGetAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RunWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkloadResponse) Reset() {
	*x = RunWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadResponse) ProtoMessage() {}

func (x *RunWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RunWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{6}
}

type CheckpointWorkloadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Atespace               string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName              string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid               string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,4,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath              string                 `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// An object storage URI prefix below which the checkpoint data will be
	// stored.
	//
	// The structure of the checkpoint should generally be treated as opaque. For
	// gVisor, the checkpoint consists of a checkpoint.img file that contains the
	// memory, sentry state, and filesystem deltas.
	//
	// For example: "gs://bucket/actors/1234/snapshots/5678/"
	SnapshotUriPrefix string `protobuf:"bytes,8,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	// runtime_asset_paths maps a runtime asset name to the local on-disk path
	// atelet fetched it to (see RunWorkloadRequest). Empty for gVisor.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,9,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// What content to include in the checkpoint.
	Scope         SnapshotScope `protobuf:"varint,10,opt,name=scope,proto3,enum=ateom.SnapshotScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointWorkloadRequest) Reset() {
	*x = CheckpointWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointWorkloadRequest) ProtoMessage() {}

func (x *CheckpointWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointWorkloadRequest.ProtoReflect.Descriptor instead.
func (*CheckpointWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{7}
}

func (x *CheckpointWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CheckpointWorkloadRequest) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *CheckpointWorkloadRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

type CheckpointWorkloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// snapshot_files lists the files ateom wrote into the checkpoint directory
	// (relative names) for atelet to ship to object storage. Each runtime reports
	// its own set (gVisor's image files, cloud-hypervisor's snapshot set, ...).
	SnapshotFiles []string `protobuf:"bytes,1,rep,name=snapshot_files,json=snapshotFiles,proto3" json:"snapshot_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointWorkloadResponse) Reset() {
	*x = CheckpointWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointWorkloadResponse) ProtoMessage() {}

func (x *CheckpointWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointWorkloadResponse.ProtoReflect.Descriptor instead.
func (*CheckpointWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{8}
}

func (x *CheckpointWorkloadResponse) GetSnapshotFiles() []string {
	if x != nil {
		return x.SnapshotFiles
	}
	return nil
}

type RestoreWorkloadRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Atespace  string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid  string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	// Actor resource version observed by ate-api when assigning this worker.
	ActorVersion           int64         `protobuf:"varint,11,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`
	ActorTemplateNamespace string        `protobuf:"bytes,4,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string        `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath              string        `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                   *WorkloadSpec `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// The object storage URI prefix of the snapshot to restore.
	SnapshotUriPrefix string `protobuf:"bytes,8,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	// runtime_asset_paths maps a runtime asset name to the local on-disk path
	// atelet fetched it to (see RunWorkloadRequest). Empty for gVisor.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,9,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// What content to restore from the snapshot.
	Scope SnapshotScope `protobuf:"varint,10,opt,name=scope,proto3,enum=ateom.SnapshotScope" json:"scope,omitempty"`
	// Remote egress gateway selected for this activation. When absent, actor
	// traffic uses direct egress instead of being redirected through atunnel.
	EgressGatewayAddress *string `protobuf:"bytes,12,opt,name=egress_gateway_address,json=egressGatewayAddress,proto3,oneof" json:"egress_gateway_address,omitempty"`
	// The object storage URI prefix of the ActorTemplate's golden snapshot.
	// Set only when scope is SNAPSHOT_SCOPE_DATA_ON_GOLDEN. Mirrors the
	// snapshot_uri_prefix contract (field 8).
	GoldenSnapshotUriPrefix string `protobuf:"bytes,13,opt,name=golden_snapshot_uri_prefix,json=goldenSnapshotUriPrefix,proto3" json:"golden_snapshot_uri_prefix,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RestoreWorkloadRequest) Reset() {
	*x = RestoreWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreWorkloadRequest) ProtoMessage() {}

func (x *RestoreWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RestoreWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorVersion() int64 {
	if x != nil {
		return x.ActorVersion
	}
	return 0
}

func (x *RestoreWorkloadRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestoreWorkloadRequest) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *RestoreWorkloadRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

func (x *RestoreWorkloadRequest) GetEgressGatewayAddress() string {
	if x != nil && x.EgressGatewayAddress != nil {
		return *x.EgressGatewayAddress
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetGoldenSnapshotUriPrefix() string {
	if x != nil {
		return x.GoldenSnapshotUriPrefix
	}
	return ""
}

type RestoreWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreWorkloadResponse) Reset() {
	*x = RestoreWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreWorkloadResponse) ProtoMessage() {}

func (x *RestoreWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RestoreWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{10}
}

var File_ateom_proto protoreflect.FileDescriptor

const file_ateom_proto_rawDesc = "" +
	"\n" +
	"\vateom.proto\x12\x05ateom\"\xc1\x04\n" +
	"\x12RunWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x12#\n" +
	"\ractor_version\x18\t \x01(\x03R\factorVersion\x128\n" +
	"\x18actor_template_namespace\x18\x04 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12`\n" +
	"\x13runtime_asset_paths\x18\b \x03(\v20.ateom.RunWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x129\n" +
	"\x16egress_gateway_address\x18\n" +
	" \x01(\tH\x00R\x14egressGatewayAddress\x88\x01\x01\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x19\n" +
	"\x17_egress_gateway_address\"@\n" +
	"\fWorkloadSpec\x120\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x10.ateom.ContainerR\n" +
	"containers\"\xba\x01\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x06readyz\x18\x02 \x01(\v2\r.ateom.ReadyzR\x06readyz\x12W\n" +
	"\x19durable_dir_volume_mounts\x18\x04 \x03(\v2\x1c.ateom.DurableDirVolumeMountR\x16durableDirVolumeMountsJ\x04\b\x03\x10\x04R\x13durable_dir_volumes\"W\n" +
	"\x15DurableDirVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"b\n" +
	"\x06Readyz\x12/\n" +
	"\bhttp_get\x18\x01 \x01(\v2\x14.ateom.HTTPGetActionR\ahttpGet\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"7\n" +
	"\rHTTPGetAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x15\n" +
	"\x13RunWorkloadResponse\"\xb0\x04\n" +
	"\x19CheckpointWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x128\n" +
	"\x18actor_template_namespace\x18\x04 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12.\n" +
	"\x13snapshot_uri_prefix\x18\b \x01(\tR\x11snapshotUriPrefix\x12g\n" +
	"\x13runtime_asset_paths\x18\t \x03(\v27.ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x12*\n" +
	"\x05scope\x18\n" +
	" \x01(\x0e2\x14.ateom.SnapshotScopeR\x05scope\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x1aCheckpointWorkloadResponse\x12%\n" +
	"\x0esnapshot_files\x18\x01 \x03(\tR\rsnapshotFiles\"\xe2\x05\n" +
	"\x16RestoreWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x12#\n" +
	"\ractor_version\x18\v \x01(\x03R\factorVersion\x128\n" +
	"\x18actor_template_namespace\x18\x04 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12.\n" +
	"\x13snapshot_uri_prefix\x18\b \x01(\tR\x11snapshotUriPrefix\x12d\n" +
	"\x13runtime_asset_paths\x18\t \x03(\v24.ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x12*\n" +
	"\x05scope\x18\n" +
	" \x01(\x0e2\x14.ateom.SnapshotScopeR\x05scope\x129\n" +
	"\x16egress_gateway_address\x18\f \x01(\tH\x00R\x14egressGatewayAddress\x88\x01\x01\x12;\n" +
	"\x1agolden_snapshot_uri_prefix\x18\r \x01(\tR\x17goldenSnapshotUriPrefix\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x19\n" +
	"\x17_egress_gateway_address\"\x19\n" +
	"\x17RestoreWorkloadResponse*\x84\x01\n" +
	"\rSnapshotScope\x12\x1e\n" +
	"\x1aSNAPSHOT_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_FULL\x10\x01\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_DATA\x10\x02\x12!\n" +
	"\x1dSNAPSHOT_SCOPE_DATA_ON_GOLDEN\x10\x032\x80\x02\n" +
	"\x05Ateom\x12F\n" +
	"\vRunWorkload\x12\x19.ateom.RunWorkloadRequest\x1a\x1a.ateom.RunWorkloadResponse\"\x00\x12[\n" +
	"\x12CheckpointWorkload\x12 .ateom.CheckpointWorkloadRequest\x1a!.ateom.CheckpointWorkloadResponse\"\x00\x12R\n" +
	"\x0fRestoreWorkload\x12\x1d.ateom.RestoreWorkloadRequest\x1a\x1e.ateom.RestoreWorkloadResponse\"\x00B=Z;github.com/agent-substrate/substrate/internal/proto/ateompbb\x06proto3"

var (
	file_ateom_proto_rawDescOnce sync.Once
	file_ateom_proto_rawDescData []byte
)

func file_ateom_proto_rawDescGZIP() []byte {
	file_ateom_proto_rawDescOnce.Do(func() {
		file_ateom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateom_proto_rawDesc), len(file_ateom_proto_rawDesc)))
	})
	return file_ateom_proto_rawDescData
}

var file_ateom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ateom_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ateom_proto_goTypes = []any{
	(SnapshotScope)(0),                 // 0: ateom.SnapshotScope
	(*RunWorkloadRequest)(nil),         // 1: ateom.RunWorkloadRequest
	(*WorkloadSpec)(nil),               // 2: ateom.WorkloadSpec
	(*Container)(nil),                  // 3: ateom.Container
	(*DurableDirVolumeMount)(nil),      // 4: ateom.DurableDirVolumeMount
	(*Readyz)(nil),                     // 5: ateom.Readyz
	(*HTTPGetAction)(nil),              // 6: ateom.HTTPGetAction
	(*RunWorkloadResponse)(nil),        // 7: ateom.RunWorkloadResponse
	(*CheckpointWorkloadRequest)(nil),  // 8: ateom.CheckpointWorkloadRequest
	(*CheckpointWorkloadResponse)(nil), // 9: ateom.CheckpointWorkloadResponse
	(*RestoreWorkloadRequest)(nil),     // 10: ateom.RestoreWorkloadRequest
	(*RestoreWorkloadResponse)(nil),    // 11: ateom.RestoreWorkloadResponse
	nil,                                // 12: ateom.RunWorkloadRequest.RuntimeAssetPathsEntry
	nil,                                // 13: ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntry
	nil,                                // 14: ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntry
}
var file_ateom_proto_depIdxs = []int32{
	2,  // 0: ateom.RunWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	12, // 1: ateom.RunWorkloadRequest.runtime_asset_paths:type_name -> ateom.RunWorkloadRequest.RuntimeAssetPathsEntry
	3,  // 2: ateom.WorkloadSpec.containers:type_name -> ateom.Container
	5,  // 3: ateom.Container.readyz:type_name -> ateom.Readyz
	4,  // 4: ateom.Container.durable_dir_volume_mounts:type_name -> ateom.DurableDirVolumeMount
	6,  // 5: ateom.Readyz.http_get:type_name -> ateom.HTTPGetAction
	2,  // 6: ateom.CheckpointWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	13, // 7: ateom.CheckpointWorkloadRequest.runtime_asset_paths:type_name -> ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntry
	0,  // 8: ateom.CheckpointWorkloadRequest.scope:type_name -> ateom.SnapshotScope
	2,  // 9: ateom.RestoreWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	14, // 10: ateom.RestoreWorkloadRequest.runtime_asset_paths:type_name -> ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntry
	0,  // 11: ateom.RestoreWorkloadRequest.scope:type_name -> ateom.SnapshotScope
	1,  // 12: ateom.Ateom.RunWorkload:input_type -> ateom.RunWorkloadRequest
	8,  // 13: ateom.Ateom.CheckpointWorkload:input_type -> ateom.CheckpointWorkloadRequest
	10, // 14: ateom.Ateom.RestoreWorkload:input_type -> ateom.RestoreWorkloadRequest
	7,  // 15: ateom.Ateom.RunWorkload:output_type -> ateom.RunWorkloadResponse
	9,  // 16: ateom.Ateom.CheckpointWorkload:output_type -> ateom.CheckpointWorkloadResponse
	11, // 17: ateom.Ateom.RestoreWorkload:output_type -> ateom.RestoreWorkloadResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ateom_proto_init() }
func file_ateom_proto_init() {
	if File_ateom_proto != nil {
		return
	}
	file_ateom_proto_msgTypes[0].OneofWrappers = []any{}
	file_ateom_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateom_proto_rawDesc), len(file_ateom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ateom_proto_goTypes,
		DependencyIndexes: file_ateom_proto_depIdxs,
		EnumInfos:         file_ateom_proto_enumTypes,
		MessageInfos:      file_ateom_proto_msgTypes,
	}.Build()
	File_ateom_proto = out.File
	file_ateom_proto_goTypes = nil
	file_ateom_proto_depIdxs = nil
}
