// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: ateom.proto

package ateompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotScope int32

const (
	// Not valid option; should never happen.
	SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED SnapshotScope = 0
	// Capture process memory plus the full filesystem delta on top of the OCI
	// image (including any attached DurableDir volumes).
	SnapshotScope_SNAPSHOT_SCOPE_FULL SnapshotScope = 1
	// Capture only the contents of attached volumes that support snapshots
	// (currently DurableDir-typed volumes). Memory and the rest of rootfs are
	// excluded.
	SnapshotScope_SNAPSHOT_SCOPE_DATA SnapshotScope = 2
	// Restore-only: restore the ActorTemplate's golden snapshot's guest state
	// (memory + full filesystem delta) combined with the snapshot's durable
	// data. Never valid for CheckpointWorkload — snapshots only ever capture
	// FULL or DATA; the control plane selects this scope at restore per the
	// template's onResume configuration.
	SnapshotScope_SNAPSHOT_SCOPE_DATA_ON_GOLDEN SnapshotScope = 3
)

// Enum value maps for SnapshotScope.
var (
	SnapshotScope_name = map[int32]string{
		0: "SNAPSHOT_SCOPE_UNSPECIFIED",
		1: "SNAPSHOT_SCOPE_FULL",
		2: "SNAPSHOT_SCOPE_DATA",
		3: "SNAPSHOT_SCOPE_DATA_ON_GOLDEN",
	}
	SnapshotScope_value = map[string]int32{
		"SNAPSHOT_SCOPE_UNSPECIFIED":    0,
		"SNAPSHOT_SCOPE_FULL":           1,
		"SNAPSHOT_SCOPE_DATA":           2,
		"SNAPSHOT_SCOPE_DATA_ON_GOLDEN": 3,
	}
)

func (x SnapshotScope) Enum() *SnapshotScope {
	p := new(SnapshotScope)
	*p = x
	return p
}

func (x SnapshotScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotScope) Descriptor() protoreflect.EnumDescriptor {
	return file_ateom_proto_enumTypes[0].Descriptor()
}

func (SnapshotScope) Type() protoreflect.EnumType {
	return &file_ateom_proto_enumTypes[0]
}

func (x SnapshotScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotScope.Descriptor instead.
func (SnapshotScope) EnumDescriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{0}
}

// SandboxClass is the sandbox runtime family that produced a sample. Mirrors
// the ate.dev/v1alpha1 SandboxClass the WorkerPool and ActorTemplate are
// configured with; an ateom binary only ever reports its own.
type SandboxClass int32

const (
	SandboxClass_SANDBOX_CLASS_UNSPECIFIED SandboxClass = 0
	// gVisor / runsc (cmd/ateom-gvisor).
	SandboxClass_SANDBOX_CLASS_GVISOR SandboxClass = 1
	// Micro-VM (cmd/ateom-microvm).
	SandboxClass_SANDBOX_CLASS_MICROVM SandboxClass = 2
)

// Enum value maps for SandboxClass.
var (
	SandboxClass_name = map[int32]string{
		0: "SANDBOX_CLASS_UNSPECIFIED",
		1: "SANDBOX_CLASS_GVISOR",
		2: "SANDBOX_CLASS_MICROVM",
	}
	SandboxClass_value = map[string]int32{
		"SANDBOX_CLASS_UNSPECIFIED": 0,
		"SANDBOX_CLASS_GVISOR":      1,
		"SANDBOX_CLASS_MICROVM":     2,
	}
)

func (x SandboxClass) Enum() *SandboxClass {
	p := new(SandboxClass)
	*p = x
	return p
}

func (x SandboxClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxClass) Descriptor() protoreflect.EnumDescriptor {
	return file_ateom_proto_enumTypes[1].Descriptor()
}

func (SandboxClass) Type() protoreflect.EnumType {
	return &file_ateom_proto_enumTypes[1]
}

func (x SandboxClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxClass.Descriptor instead.
func (SandboxClass) EnumDescriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{1}
}

// StatsSource is how a sample's measurements were obtained. The two are not
// measured the same way and should not be compared against each other as though
// they were.
type StatsSource int32

const (
	// No measurement was taken.
	StatsSource_STATS_SOURCE_UNSPECIFIED StatsSource = 0
	// Read from the sandbox's cgroup on the host.
	StatsSource_STATS_SOURCE_CGROUP StatsSource = 1
	// Read from inside the guest, over the guest agent's vsock connection. What
	// it counts is the workload's own containers, as the guest kernel accounts
	// for them: the guest kernel itself, the agent, and the VMM process on the
	// host are overhead this source cannot see. The cgroup source above is the
	// other way round -- the sandbox's host process is one process, so its
	// runtime's overhead is charged along with the workload's.
	StatsSource_STATS_SOURCE_GUEST_AGENT StatsSource = 2
)

// Enum value maps for StatsSource.
var (
	StatsSource_name = map[int32]string{
		0: "STATS_SOURCE_UNSPECIFIED",
		1: "STATS_SOURCE_CGROUP",
		2: "STATS_SOURCE_GUEST_AGENT",
	}
	StatsSource_value = map[string]int32{
		"STATS_SOURCE_UNSPECIFIED": 0,
		"STATS_SOURCE_CGROUP":      1,
		"STATS_SOURCE_GUEST_AGENT": 2,
	}
)

func (x StatsSource) Enum() *StatsSource {
	p := new(StatsSource)
	*p = x
	return p
}

func (x StatsSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatsSource) Descriptor() protoreflect.EnumDescriptor {
	return file_ateom_proto_enumTypes[2].Descriptor()
}

func (StatsSource) Type() protoreflect.EnumType {
	return &file_ateom_proto_enumTypes[2]
}

func (x StatsSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatsSource.Descriptor instead.
func (StatsSource) EnumDescriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{2}
}

// ActorDirs is the set of per-actor directories atelet prepares on the volume
// it shares with ateom. ateom takes them from the RPC instead of deriving
// them from the actor UID.
// Every directory is under root_dir.
type ActorDirs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actor's own directory.
	RootDir string `protobuf:"bytes,1,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	// Holds one OCI bundle per container, named after the container.
	OciBundleDir string `protobuf:"bytes,2,opt,name=oci_bundle_dir,json=ociBundleDir,proto3" json:"oci_bundle_dir,omitempty"`
	// Where CheckpointWorkload writes the snapshot files.
	CheckpointDir string `protobuf:"bytes,3,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	// Where the snapshot files RestoreWorkload reads have been downloaded to.
	RestoreDir string `protobuf:"bytes,4,opt,name=restore_dir,json=restoreDir,proto3" json:"restore_dir,omitempty"`
	// Holds one subdirectory per durable-dir volume.
	DurableDirVolumeMountsDir string `protobuf:"bytes,5,opt,name=durable_dir_volume_mounts_dir,json=durableDirVolumeMountsDir,proto3" json:"durable_dir_volume_mounts_dir,omitempty"`
	// Holds one subdirectory per system-info volume.
	SystemInfoVolumeRootsDir string `protobuf:"bytes,6,opt,name=system_info_volume_roots_dir,json=systemInfoVolumeRootsDir,proto3" json:"system_info_volume_roots_dir,omitempty"`
	// Holds one mount point per CSI volume.
	VolumesDir    string `protobuf:"bytes,7,opt,name=volumes_dir,json=volumesDir,proto3" json:"volumes_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorDirs) Reset() {
	*x = ActorDirs{}
	mi := &file_ateom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorDirs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDirs) ProtoMessage() {}

func (x *ActorDirs) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDirs.ProtoReflect.Descriptor instead.
func (*ActorDirs) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{0}
}

func (x *ActorDirs) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *ActorDirs) GetOciBundleDir() string {
	if x != nil {
		return x.OciBundleDir
	}
	return ""
}

func (x *ActorDirs) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

func (x *ActorDirs) GetRestoreDir() string {
	if x != nil {
		return x.RestoreDir
	}
	return ""
}

func (x *ActorDirs) GetDurableDirVolumeMountsDir() string {
	if x != nil {
		return x.DurableDirVolumeMountsDir
	}
	return ""
}

func (x *ActorDirs) GetSystemInfoVolumeRootsDir() string {
	if x != nil {
		return x.SystemInfoVolumeRootsDir
	}
	return ""
}

func (x *ActorDirs) GetVolumesDir() string {
	if x != nil {
		return x.VolumesDir
	}
	return ""
}

type TerminateWorkloadRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Atespace              string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid              string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateAtespace string                 `protobuf:"bytes,4,opt,name=actor_template_atespace,json=actorTemplateAtespace,proto3" json:"actor_template_atespace,omitempty"`
	ActorTemplateName     string                 `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath             string                 `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                  *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	ActorDirs             *ActorDirs             `protobuf:"bytes,8,opt,name=actor_dirs,json=actorDirs,proto3" json:"actor_dirs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TerminateWorkloadRequest) Reset() {
	*x = TerminateWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateWorkloadRequest) ProtoMessage() {}

func (x *TerminateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*TerminateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{1}
}

func (x *TerminateWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetActorTemplateAtespace() string {
	if x != nil {
		return x.ActorTemplateAtespace
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *TerminateWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *TerminateWorkloadRequest) GetActorDirs() *ActorDirs {
	if x != nil {
		return x.ActorDirs
	}
	return nil
}

type TerminateWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateWorkloadResponse) Reset() {
	*x = TerminateWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateWorkloadResponse) ProtoMessage() {}

func (x *TerminateWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateWorkloadResponse.ProtoReflect.Descriptor instead.
func (*TerminateWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{2}
}

type RunWorkloadRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Atespace              string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid              string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateAtespace string                 `protobuf:"bytes,4,opt,name=actor_template_atespace,json=actorTemplateAtespace,proto3" json:"actor_template_atespace,omitempty"`
	ActorTemplateName     string                 `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath             string                 `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                  *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// runtime_asset_paths maps a runtime asset name (e.g. "cloud-hypervisor",
	// "virtiofsd", "kata-kernel", "kata-image")
	// to the local on-disk path atelet fetched it to (content-addressed, like
	// runsc_path). Empty for the gVisor runtime, which uses runsc_path.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,8,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When absent the actor has no egress: its TCP is captured and refused.
	EgressGateway *EgressGateway `protobuf:"bytes,10,opt,name=egress_gateway,json=egressGateway,proto3,oneof" json:"egress_gateway,omitempty"`
	// The actor's declared size, from the ActorTemplate's resource limits. ateom
	// sizes the sandbox to these (cgroup caps via the OCI spec, and for the
	// micro-VM the VM's vCPU count and memory). Zero means "unset": keep the
	// runtime default (unlimited for gVisor, ateom's own default for the micro-VM).
	CpuMilli      int64      `protobuf:"varint,11,opt,name=cpu_milli,json=cpuMilli,proto3" json:"cpu_milli,omitempty"`          // CPU limit in millicores (1000 = one core).
	MemoryBytes   int64      `protobuf:"varint,12,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // Memory limit in bytes.
	ActorDirs     *ActorDirs `protobuf:"bytes,13,opt,name=actor_dirs,json=actorDirs,proto3" json:"actor_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkloadRequest) Reset() {
	*x = RunWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadRequest) ProtoMessage() {}

func (x *RunWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RunWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{3}
}

func (x *RunWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorTemplateAtespace() string {
	if x != nil {
		return x.ActorTemplateAtespace
	}
	return ""
}

func (x *RunWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RunWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *RunWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RunWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *RunWorkloadRequest) GetEgressGateway() *EgressGateway {
	if x != nil {
		return x.EgressGateway
	}
	return nil
}

func (x *RunWorkloadRequest) GetCpuMilli() int64 {
	if x != nil {
		return x.CpuMilli
	}
	return 0
}

func (x *RunWorkloadRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RunWorkloadRequest) GetActorDirs() *ActorDirs {
	if x != nil {
		return x.ActorDirs
	}
	return nil
}

// EgressGateway configures tunneled egress for one actor activation.
type EgressGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is required and identifies the remote gateway as an IP address or
	// DNS name followed by its port.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressGateway) Reset() {
	*x = EgressGateway{}
	mi := &file_ateom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressGateway) ProtoMessage() {}

func (x *EgressGateway) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressGateway.ProtoReflect.Descriptor instead.
func (*EgressGateway) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{4}
}

func (x *EgressGateway) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// WorkloadSpec parallels Pod, but with far fewer configurable fields.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_ateom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WakeupProbe *WakeupProbe           `protobuf:"bytes,2,opt,name=wakeup_probe,json=wakeupProbe,proto3" json:"wakeup_probe,omitempty"`
	// durable_dir_volume_mounts are the durable-dir volumes this container
	// mounts, if any.
	DurableDirVolumeMounts []*DurableDirVolumeMount `protobuf:"bytes,3,rep,name=durable_dir_volume_mounts,json=durableDirVolumeMounts,proto3" json:"durable_dir_volume_mounts,omitempty"`
	// csi_volume_mounts are the CSI volumes this container mounts, if any.
	CsiVolumeMounts []*VolumeMount `protobuf:"bytes,4,rep,name=csi_volume_mounts,json=csiVolumeMounts,proto3" json:"csi_volume_mounts,omitempty"`
	// system_info_volume_mounts are the system-info volumes this container
	// mounts, if any. Contents are generated by atelet on the host; the
	// container sees them read-only.
	SystemInfoVolumeMounts []*SystemInfoVolumeMount `protobuf:"bytes,5,rep,name=system_info_volume_mounts,json=systemInfoVolumeMounts,proto3" json:"system_info_volume_mounts,omitempty"`
	// image_volume_mounts are the image volumes this container mounts, if any.
	ImageVolumeMounts []*ImageVolumeMount `protobuf:"bytes,6,rep,name=image_volume_mounts,json=imageVolumeMounts,proto3" json:"image_volume_mounts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_ateom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetWakeupProbe() *WakeupProbe {
	if x != nil {
		return x.WakeupProbe
	}
	return nil
}

func (x *Container) GetDurableDirVolumeMounts() []*DurableDirVolumeMount {
	if x != nil {
		return x.DurableDirVolumeMounts
	}
	return nil
}

func (x *Container) GetCsiVolumeMounts() []*VolumeMount {
	if x != nil {
		return x.CsiVolumeMounts
	}
	return nil
}

func (x *Container) GetSystemInfoVolumeMounts() []*SystemInfoVolumeMount {
	if x != nil {
		return x.SystemInfoVolumeMounts
	}
	return nil
}

func (x *Container) GetImageVolumeMounts() []*ImageVolumeMount {
	if x != nil {
		return x.ImageVolumeMounts
	}
	return nil
}

// VolumeMount is one volume mounted into a container.
type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeName    string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_ateom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

// DurableDirVolumeMount is one durable-dir volume mounted into a container.
type DurableDirVolumeMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_name is the name the ActorTemplate gave the volume. It selects the
	// per-volume directory atelet prepared for the actor on the host.
	VolumeName string `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// mount_path is where the container sees the volume.
	MountPath     string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableDirVolumeMount) Reset() {
	*x = DurableDirVolumeMount{}
	mi := &file_ateom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableDirVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableDirVolumeMount) ProtoMessage() {}

func (x *DurableDirVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableDirVolumeMount.ProtoReflect.Descriptor instead.
func (*DurableDirVolumeMount) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{8}
}

func (x *DurableDirVolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *DurableDirVolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

// SystemInfoVolumeMount is one system-info volume mounted (read-only) into a
// container. Unlike durable-dir volumes, system-info contents are generated
// by atelet on every Run/Restore and are never captured into snapshots.
type SystemInfoVolumeMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_name is the name the ActorTemplate gave the volume. It selects the
	// per-volume directory atelet prepared for the actor on the host.
	VolumeName string `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// mount_path is where the container sees the volume.
	MountPath     string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoVolumeMount) Reset() {
	*x = SystemInfoVolumeMount{}
	mi := &file_ateom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoVolumeMount) ProtoMessage() {}

func (x *SystemInfoVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoVolumeMount.ProtoReflect.Descriptor instead.
func (*SystemInfoVolumeMount) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{9}
}

func (x *SystemInfoVolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *SystemInfoVolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

// ImageVolumeMount is one image volume mounted into a container. ateom uses
// these to construct the container's volume mounts — each names the volume
// and its destination path.
type ImageVolumeMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_name is the name the ActorTemplate gave the volume.
	VolumeName string `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// mount_path is where the container sees the volume.
	MountPath     string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVolumeMount) Reset() {
	*x = ImageVolumeMount{}
	mi := &file_ateom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVolumeMount) ProtoMessage() {}

func (x *ImageVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVolumeMount.ProtoReflect.Descriptor instead.
func (*ImageVolumeMount) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{10}
}

func (x *ImageVolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *ImageVolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

// WakeupProbe describes how to check that a container is ready to serve.
// Only HTTP is supported today.
type WakeupProbe struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HttpGet *HTTPGetAction         `protobuf:"bytes,1,opt,name=http_get,json=httpGet,proto3" json:"http_get,omitempty"`
	// How long to keep polling before giving up and failing the actor start.
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WakeupProbe) Reset() {
	*x = WakeupProbe{}
	mi := &file_ateom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeupProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeupProbe) ProtoMessage() {}

func (x *WakeupProbe) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeupProbe.ProtoReflect.Descriptor instead.
func (*WakeupProbe) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{11}
}

func (x *WakeupProbe) GetHttpGet() *HTTPGetAction {
	if x != nil {
		return x.HttpGet
	}
	return nil
}

func (x *WakeupProbe) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// HTTPGetAction performs an HTTP GET against the container.
type HTTPGetAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to access on the HTTP server.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// TCP port to connect to (1..65535).
	Port          int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPGetAction) Reset() {
	*x = HTTPGetAction{}
	mi := &file_ateom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetAction) ProtoMessage() {}

func (x *HTTPGetAction) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetAction.ProtoReflect.Descriptor instead.
func (*HTTPGetAction) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{12}
}

func (x *HTTPGetAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RunWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkloadResponse) Reset() {
	*x = RunWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadResponse) ProtoMessage() {}

func (x *RunWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RunWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{13}
}

type CheckpointWorkloadRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Atespace              string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid              string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateAtespace string                 `protobuf:"bytes,4,opt,name=actor_template_atespace,json=actorTemplateAtespace,proto3" json:"actor_template_atespace,omitempty"`
	ActorTemplateName     string                 `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath             string                 `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                  *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// The object storage URI of the snapshot to write. Object names are appended
	// to it, so it addresses the snapshot as a whole rather than any one object.
	//
	// The structure of the checkpoint should generally be treated as opaque. For
	// gVisor, the checkpoint consists of a checkpoint.img file that contains the
	// memory, sentry state, and filesystem deltas.
	//
	// The control plane sends an ActorSnapshot's snapshot_uri, which sits under
	// the prefix of the resource that owns the snapshot. For example:
	// "gs://bucket/root/atespaces/team-a/actors/<actor uid>/snapshots/5678".
	SnapshotUri string `protobuf:"bytes,8,opt,name=snapshot_uri,json=snapshotUri,proto3" json:"snapshot_uri,omitempty"`
	// runtime_asset_paths maps a runtime asset name to the local on-disk path
	// atelet fetched it to (see RunWorkloadRequest). Empty for gVisor.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,9,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// What content to include in the checkpoint.
	Scope         SnapshotScope `protobuf:"varint,10,opt,name=scope,proto3,enum=ateom.SnapshotScope" json:"scope,omitempty"`
	ActorDirs     *ActorDirs    `protobuf:"bytes,11,opt,name=actor_dirs,json=actorDirs,proto3" json:"actor_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointWorkloadRequest) Reset() {
	*x = CheckpointWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointWorkloadRequest) ProtoMessage() {}

func (x *CheckpointWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointWorkloadRequest.ProtoReflect.Descriptor instead.
func (*CheckpointWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{14}
}

func (x *CheckpointWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorTemplateAtespace() string {
	if x != nil {
		return x.ActorTemplateAtespace
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CheckpointWorkloadRequest) GetSnapshotUri() string {
	if x != nil {
		return x.SnapshotUri
	}
	return ""
}

func (x *CheckpointWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *CheckpointWorkloadRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

func (x *CheckpointWorkloadRequest) GetActorDirs() *ActorDirs {
	if x != nil {
		return x.ActorDirs
	}
	return nil
}

type CheckpointWorkloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// snapshot_files lists the files ateom wrote into the checkpoint directory
	// (relative names) for atelet to ship to object storage. Each runtime reports
	// its own set (gVisor's image files, cloud-hypervisor's snapshot set, ...).
	SnapshotFiles []string `protobuf:"bytes,1,rep,name=snapshot_files,json=snapshotFiles,proto3" json:"snapshot_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointWorkloadResponse) Reset() {
	*x = CheckpointWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointWorkloadResponse) ProtoMessage() {}

func (x *CheckpointWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointWorkloadResponse.ProtoReflect.Descriptor instead.
func (*CheckpointWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{15}
}

func (x *CheckpointWorkloadResponse) GetSnapshotFiles() []string {
	if x != nil {
		return x.SnapshotFiles
	}
	return nil
}

type RestoreWorkloadRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Atespace              string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName             string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid              string                 `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateAtespace string                 `protobuf:"bytes,4,opt,name=actor_template_atespace,json=actorTemplateAtespace,proto3" json:"actor_template_atespace,omitempty"`
	ActorTemplateName     string                 `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	RunscPath             string                 `protobuf:"bytes,6,opt,name=runsc_path,json=runscPath,proto3" json:"runsc_path,omitempty"`
	Spec                  *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// The object storage URI of the snapshot to restore. Object names are
	// appended to it; it addresses the snapshot, not any one object.
	SnapshotUri string `protobuf:"bytes,8,opt,name=snapshot_uri,json=snapshotUri,proto3" json:"snapshot_uri,omitempty"`
	// runtime_asset_paths maps a runtime asset name to the local on-disk path
	// atelet fetched it to (see RunWorkloadRequest). Empty for gVisor.
	RuntimeAssetPaths map[string]string `protobuf:"bytes,9,rep,name=runtime_asset_paths,json=runtimeAssetPaths,proto3" json:"runtime_asset_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// What content to restore from the snapshot.
	Scope SnapshotScope `protobuf:"varint,10,opt,name=scope,proto3,enum=ateom.SnapshotScope" json:"scope,omitempty"`
	// When absent the actor has no egress: its TCP is captured and refused.
	EgressGateway *EgressGateway `protobuf:"bytes,12,opt,name=egress_gateway,json=egressGateway,proto3,oneof" json:"egress_gateway,omitempty"`
	// The object storage URI of the ActorTemplate's golden snapshot.
	// Set only when scope is SNAPSHOT_SCOPE_DATA_ON_GOLDEN. Mirrors the
	// snapshot_uri contract (field 8).
	GoldenSnapshotUri string `protobuf:"bytes,13,opt,name=golden_snapshot_uri,json=goldenSnapshotUri,proto3" json:"golden_snapshot_uri,omitempty"`
	// The actor's declared size, from the ActorTemplate's resource limits. Used to
	// (re)size the sandbox on a DATA-scope restore (fresh guest container). On a
	// FULL micro-VM restore the size baked into the snapshot is authoritative and
	// these are ignored. Zero means "unset": keep the runtime default.
	CpuMilli      int64      `protobuf:"varint,14,opt,name=cpu_milli,json=cpuMilli,proto3" json:"cpu_milli,omitempty"`          // CPU limit in millicores (1000 = one core).
	MemoryBytes   int64      `protobuf:"varint,15,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // Memory limit in bytes.
	ActorDirs     *ActorDirs `protobuf:"bytes,16,opt,name=actor_dirs,json=actorDirs,proto3" json:"actor_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreWorkloadRequest) Reset() {
	*x = RestoreWorkloadRequest{}
	mi := &file_ateom_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreWorkloadRequest) ProtoMessage() {}

func (x *RestoreWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RestoreWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreWorkloadRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorTemplateAtespace() string {
	if x != nil {
		return x.ActorTemplateAtespace
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetRunscPath() string {
	if x != nil {
		return x.RunscPath
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestoreWorkloadRequest) GetSnapshotUri() string {
	if x != nil {
		return x.SnapshotUri
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetRuntimeAssetPaths() map[string]string {
	if x != nil {
		return x.RuntimeAssetPaths
	}
	return nil
}

func (x *RestoreWorkloadRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

func (x *RestoreWorkloadRequest) GetEgressGateway() *EgressGateway {
	if x != nil {
		return x.EgressGateway
	}
	return nil
}

func (x *RestoreWorkloadRequest) GetGoldenSnapshotUri() string {
	if x != nil {
		return x.GoldenSnapshotUri
	}
	return ""
}

func (x *RestoreWorkloadRequest) GetCpuMilli() int64 {
	if x != nil {
		return x.CpuMilli
	}
	return 0
}

func (x *RestoreWorkloadRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RestoreWorkloadRequest) GetActorDirs() *ActorDirs {
	if x != nil {
		return x.ActorDirs
	}
	return nil
}

type RestoreWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreWorkloadResponse) Reset() {
	*x = RestoreWorkloadResponse{}
	mi := &file_ateom_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreWorkloadResponse) ProtoMessage() {}

func (x *RestoreWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RestoreWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{17}
}

type GetWorkloadStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actor the caller believes is executing here. A worker can be recycled
	// between the caller's view of the world and this call, so ateom answers
	// NOT_FOUND on a mismatch rather than reporting a different actor's numbers
	// under the requested actor's identity.
	ActorUid      string `protobuf:"bytes,1,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatsRequest) Reset() {
	*x = GetWorkloadStatsRequest{}
	mi := &file_ateom_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatsRequest) ProtoMessage() {}

func (x *GetWorkloadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatsRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{18}
}

func (x *GetWorkloadStatsRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

// WorkloadStatsSample is one resource-usage sample for an executing workload,
// shared by both stats reads. The unit of measurement is the SANDBOX, which
// today equals the actor. Per-container attribution is not reported: the
// micro-VM source could give it, since the guest keeps a cgroup per container
// and ateom sums them, but the gVisor source cannot split one at all without
// the sentry's own accounting, and a field only one runtime could ever fill
// would be worse than none.
type WorkloadStatsSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the measured actor, retained by ateom from the
	// RunWorkloadRequest / RestoreWorkloadRequest that started it. Echoed back so
	// the caller can attribute the sample without holding its own mapping from
	// worker to actor.
	Atespace              string `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName             string `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid              string `protobuf:"bytes,3,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateAtespace string `protobuf:"bytes,4,opt,name=actor_template_atespace,json=actorTemplateAtespace,proto3" json:"actor_template_atespace,omitempty"`
	ActorTemplateName     string `protobuf:"bytes,5,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	// The sandbox runtime family that produced this sample.
	SandboxClass SandboxClass `protobuf:"varint,6,opt,name=sandbox_class,json=sandboxClass,proto3,enum=ateom.SandboxClass" json:"sandbox_class,omitempty"`
	// How the measurements below were obtained.
	Source StatsSource `protobuf:"varint,7,opt,name=source,proto3,enum=ateom.StatsSource" json:"source,omitempty"`
	// Measurements. All four are zero when source is STATS_SOURCE_UNSPECIFIED,
	// which means "not measured" rather than "measured as zero".
	//
	// memory_current_bytes and memory_working_set_bytes are absolute.
	MemoryCurrentBytes uint64 `protobuf:"varint,8,opt,name=memory_current_bytes,json=memoryCurrentBytes,proto3" json:"memory_current_bytes,omitempty"`
	// High-water mark of memory_current_bytes, as the source reports it: the
	// cgroup source restarts it on a restore, the guest-agent source brings the
	// guest's own back with it. Also zero when the runtime cannot report a peak:
	// the cgroup source reads memory.peak, which only exists on Linux 5.19 and
	// later.
	MemoryPeakBytes uint64 `protobuf:"varint,9,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3" json:"memory_peak_bytes,omitempty"`
	// memory_current_bytes less the reclaimable page cache, floored at zero. This
	// is the figure to compare against a memory limit; memory_current_bytes
	// drifts upward with cache the kernel would drop for free under pressure.
	MemoryWorkingSetBytes uint64 `protobuf:"varint,10,opt,name=memory_working_set_bytes,json=memoryWorkingSetBytes,proto3" json:"memory_working_set_bytes,omitempty"`
	// Cumulative CPU time since the activation began (epoch_unix_nano), for
	// every source. The cgroup source restarts on its own; the guest-agent
	// source is rebased on its first read after a restore, since the guest's
	// counters survive in guest RAM. An ateom that leaves epoch_unix_nano at zero
	// also sends the raw guest counter. A lifetime figure is the sum over epochs
	// of each epoch's highest value.
	CpuUsageUsec       uint64 `protobuf:"varint,11,opt,name=cpu_usage_usec,json=cpuUsageUsec,proto3" json:"cpu_usage_usec,omitempty"`
	ObservedAtUnixNano int64  `protobuf:"varint,12,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	// The activation this sample belongs to, as the unix-nano time it began. A
	// Run or Restore starts one. Zero from an ateom that does not set it.
	EpochUnixNano int64 `protobuf:"varint,13,opt,name=epoch_unix_nano,json=epochUnixNano,proto3" json:"epoch_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatsSample) Reset() {
	*x = WorkloadStatsSample{}
	mi := &file_ateom_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatsSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatsSample) ProtoMessage() {}

func (x *WorkloadStatsSample) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatsSample.ProtoReflect.Descriptor instead.
func (*WorkloadStatsSample) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{19}
}

func (x *WorkloadStatsSample) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *WorkloadStatsSample) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *WorkloadStatsSample) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *WorkloadStatsSample) GetActorTemplateAtespace() string {
	if x != nil {
		return x.ActorTemplateAtespace
	}
	return ""
}

func (x *WorkloadStatsSample) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *WorkloadStatsSample) GetSandboxClass() SandboxClass {
	if x != nil {
		return x.SandboxClass
	}
	return SandboxClass_SANDBOX_CLASS_UNSPECIFIED
}

func (x *WorkloadStatsSample) GetSource() StatsSource {
	if x != nil {
		return x.Source
	}
	return StatsSource_STATS_SOURCE_UNSPECIFIED
}

func (x *WorkloadStatsSample) GetMemoryCurrentBytes() uint64 {
	if x != nil {
		return x.MemoryCurrentBytes
	}
	return 0
}

func (x *WorkloadStatsSample) GetMemoryPeakBytes() uint64 {
	if x != nil {
		return x.MemoryPeakBytes
	}
	return 0
}

func (x *WorkloadStatsSample) GetMemoryWorkingSetBytes() uint64 {
	if x != nil {
		return x.MemoryWorkingSetBytes
	}
	return 0
}

func (x *WorkloadStatsSample) GetCpuUsageUsec() uint64 {
	if x != nil {
		return x.CpuUsageUsec
	}
	return 0
}

func (x *WorkloadStatsSample) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *WorkloadStatsSample) GetEpochUnixNano() int64 {
	if x != nil {
		return x.EpochUnixNano
	}
	return 0
}

type GetWorkloadStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sample        *WorkloadStatsSample   `protobuf:"bytes,1,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatsResponse) Reset() {
	*x = GetWorkloadStatsResponse{}
	mi := &file_ateom_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatsResponse) ProtoMessage() {}

func (x *GetWorkloadStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatsResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{20}
}

func (x *GetWorkloadStatsResponse) GetSample() *WorkloadStatsSample {
	if x != nil {
		return x.Sample
	}
	return nil
}

type GetActiveWorkloadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorkloadStatsRequest) Reset() {
	*x = GetActiveWorkloadStatsRequest{}
	mi := &file_ateom_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorkloadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorkloadStatsRequest) ProtoMessage() {}

func (x *GetActiveWorkloadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorkloadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveWorkloadStatsRequest) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{21}
}

type GetActiveWorkloadStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per workload this ateom is executing; empty when it is
	// "available". Each sample is self-describing (see the attribution rule on
	// the rpc); an entry with source = STATS_SOURCE_UNSPECIFIED is a workload
	// with no numbers to give yet (boot, restore, teardown, or a lifecycle
	// transition underneath the read) -- skip its measurements and take the
	// next sample. An ateom serves one actor at a time today, so the list holds
	// at most one entry until multi-actor workers land; consumers must not
	// assume that.
	Samples       []*WorkloadStatsSample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorkloadStatsResponse) Reset() {
	*x = GetActiveWorkloadStatsResponse{}
	mi := &file_ateom_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorkloadStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorkloadStatsResponse) ProtoMessage() {}

func (x *GetActiveWorkloadStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateom_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorkloadStatsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveWorkloadStatsResponse) Descriptor() ([]byte, []int) {
	return file_ateom_proto_rawDescGZIP(), []int{22}
}

func (x *GetActiveWorkloadStatsResponse) GetSamples() []*WorkloadStatsSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_ateom_proto protoreflect.FileDescriptor

const file_ateom_proto_rawDesc = "" +
	"\n" +
	"\vateom.proto\x12\x05ateom\"\xb7\x02\n" +
	"\tActorDirs\x12\x19\n" +
	"\broot_dir\x18\x01 \x01(\tR\arootDir\x12$\n" +
	"\x0eoci_bundle_dir\x18\x02 \x01(\tR\fociBundleDir\x12%\n" +
	"\x0echeckpoint_dir\x18\x03 \x01(\tR\rcheckpointDir\x12\x1f\n" +
	"\vrestore_dir\x18\x04 \x01(\tR\n" +
	"restoreDir\x12@\n" +
	"\x1ddurable_dir_volume_mounts_dir\x18\x05 \x01(\tR\x19durableDirVolumeMountsDir\x12>\n" +
	"\x1csystem_info_volume_roots_dir\x18\x06 \x01(\tR\x18systemInfoVolumeRootsDir\x12\x1f\n" +
	"\vvolumes_dir\x18\a \x01(\tR\n" +
	"volumesDir\"\xd3\x02\n" +
	"\x18TerminateWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x126\n" +
	"\x17actor_template_atespace\x18\x04 \x01(\tR\x15actorTemplateAtespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12/\n" +
	"\n" +
	"actor_dirs\x18\b \x01(\v2\x10.ateom.ActorDirsR\tactorDirs\"\x1b\n" +
	"\x19TerminateWorkloadResponse\"\x8a\x05\n" +
	"\x12RunWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x126\n" +
	"\x17actor_template_atespace\x18\x04 \x01(\tR\x15actorTemplateAtespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12`\n" +
	"\x13runtime_asset_paths\x18\b \x03(\v20.ateom.RunWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x12@\n" +
	"\x0eegress_gateway\x18\n" +
	" \x01(\v2\x14.ateom.EgressGatewayH\x00R\regressGateway\x88\x01\x01\x12\x1b\n" +
	"\tcpu_milli\x18\v \x01(\x03R\bcpuMilli\x12!\n" +
	"\fmemory_bytes\x18\f \x01(\x03R\vmemoryBytes\x12/\n" +
	"\n" +
	"actor_dirs\x18\r \x01(\v2\x10.ateom.ActorDirsR\tactorDirs\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_egress_gateway\")\n" +
	"\rEgressGateway\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"@\n" +
	"\fWorkloadSpec\x120\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x10.ateom.ContainerR\n" +
	"containers\"\x91\x03\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\fwakeup_probe\x18\x02 \x01(\v2\x12.ateom.WakeupProbeR\vwakeupProbe\x12W\n" +
	"\x19durable_dir_volume_mounts\x18\x03 \x03(\v2\x1c.ateom.DurableDirVolumeMountR\x16durableDirVolumeMounts\x12>\n" +
	"\x11csi_volume_mounts\x18\x04 \x03(\v2\x12.ateom.VolumeMountR\x0fcsiVolumeMounts\x12W\n" +
	"\x19system_info_volume_mounts\x18\x05 \x03(\v2\x1c.ateom.SystemInfoVolumeMountR\x16systemInfoVolumeMounts\x12G\n" +
	"\x13image_volume_mounts\x18\x06 \x03(\v2\x17.ateom.ImageVolumeMountR\x11imageVolumeMounts\"M\n" +
	"\vVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"W\n" +
	"\x15DurableDirVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"W\n" +
	"\x15SystemInfoVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"R\n" +
	"\x10ImageVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"g\n" +
	"\vWakeupProbe\x12/\n" +
	"\bhttp_get\x18\x01 \x01(\v2\x14.ateom.HTTPGetActionR\ahttpGet\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"7\n" +
	"\rHTTPGetAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x15\n" +
	"\x13RunWorkloadResponse\"\xd2\x04\n" +
	"\x19CheckpointWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x126\n" +
	"\x17actor_template_atespace\x18\x04 \x01(\tR\x15actorTemplateAtespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12!\n" +
	"\fsnapshot_uri\x18\b \x01(\tR\vsnapshotUri\x12g\n" +
	"\x13runtime_asset_paths\x18\t \x03(\v27.ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x12*\n" +
	"\x05scope\x18\n" +
	" \x01(\x0e2\x14.ateom.SnapshotScopeR\x05scope\x12/\n" +
	"\n" +
	"actor_dirs\x18\v \x01(\v2\x10.ateom.ActorDirsR\tactorDirs\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x1aCheckpointWorkloadResponse\x12%\n" +
	"\x0esnapshot_files\x18\x01 \x03(\tR\rsnapshotFiles\"\x91\x06\n" +
	"\x16RestoreWorkloadRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x126\n" +
	"\x17actor_template_atespace\x18\x04 \x01(\tR\x15actorTemplateAtespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x12\x1d\n" +
	"\n" +
	"runsc_path\x18\x06 \x01(\tR\trunscPath\x12'\n" +
	"\x04spec\x18\a \x01(\v2\x13.ateom.WorkloadSpecR\x04spec\x12!\n" +
	"\fsnapshot_uri\x18\b \x01(\tR\vsnapshotUri\x12d\n" +
	"\x13runtime_asset_paths\x18\t \x03(\v24.ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntryR\x11runtimeAssetPaths\x12*\n" +
	"\x05scope\x18\n" +
	" \x01(\x0e2\x14.ateom.SnapshotScopeR\x05scope\x12@\n" +
	"\x0eegress_gateway\x18\f \x01(\v2\x14.ateom.EgressGatewayH\x00R\regressGateway\x88\x01\x01\x12.\n" +
	"\x13golden_snapshot_uri\x18\r \x01(\tR\x11goldenSnapshotUri\x12\x1b\n" +
	"\tcpu_milli\x18\x0e \x01(\x03R\bcpuMilli\x12!\n" +
	"\fmemory_bytes\x18\x0f \x01(\x03R\vmemoryBytes\x12/\n" +
	"\n" +
	"actor_dirs\x18\x10 \x01(\v2\x10.ateom.ActorDirsR\tactorDirs\x1aD\n" +
	"\x16RuntimeAssetPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_egress_gateway\"\x19\n" +
	"\x17RestoreWorkloadResponse\"6\n" +
	"\x17GetWorkloadStatsRequest\x12\x1b\n" +
	"\tactor_uid\x18\x01 \x01(\tR\bactorUid\"\xd3\x04\n" +
	"\x13WorkloadStatsSample\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x03 \x01(\tR\bactorUid\x126\n" +
	"\x17actor_template_atespace\x18\x04 \x01(\tR\x15actorTemplateAtespace\x12.\n" +
	"\x13actor_template_name\x18\x05 \x01(\tR\x11actorTemplateName\x128\n" +
	"\rsandbox_class\x18\x06 \x01(\x0e2\x13.ateom.SandboxClassR\fsandboxClass\x12*\n" +
	"\x06source\x18\a \x01(\x0e2\x12.ateom.StatsSourceR\x06source\x120\n" +
	"\x14memory_current_bytes\x18\b \x01(\x04R\x12memoryCurrentBytes\x12*\n" +
	"\x11memory_peak_bytes\x18\t \x01(\x04R\x0fmemoryPeakBytes\x127\n" +
	"\x18memory_working_set_bytes\x18\n" +
	" \x01(\x04R\x15memoryWorkingSetBytes\x12$\n" +
	"\x0ecpu_usage_usec\x18\v \x01(\x04R\fcpuUsageUsec\x121\n" +
	"\x15observed_at_unix_nano\x18\f \x01(\x03R\x12observedAtUnixNano\x12&\n" +
	"\x0fepoch_unix_nano\x18\r \x01(\x03R\repochUnixNano\"N\n" +
	"\x18GetWorkloadStatsResponse\x122\n" +
	"\x06sample\x18\x01 \x01(\v2\x1a.ateom.WorkloadStatsSampleR\x06sample\"\x1f\n" +
	"\x1dGetActiveWorkloadStatsRequest\"V\n" +
	"\x1eGetActiveWorkloadStatsResponse\x124\n" +
	"\asamples\x18\x01 \x03(\v2\x1a.ateom.WorkloadStatsSampleR\asamples*\x84\x01\n" +
	"\rSnapshotScope\x12\x1e\n" +
	"\x1aSNAPSHOT_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_FULL\x10\x01\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_DATA\x10\x02\x12!\n" +
	"\x1dSNAPSHOT_SCOPE_DATA_ON_GOLDEN\x10\x03*b\n" +
	"\fSandboxClass\x12\x1d\n" +
	"\x19SANDBOX_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SANDBOX_CLASS_GVISOR\x10\x01\x12\x19\n" +
	"\x15SANDBOX_CLASS_MICROVM\x10\x02*b\n" +
	"\vStatsSource\x12\x1c\n" +
	"\x18STATS_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STATS_SOURCE_CGROUP\x10\x01\x12\x1c\n" +
	"\x18STATS_SOURCE_GUEST_AGENT\x10\x022\x9a\x04\n" +
	"\x05Ateom\x12F\n" +
	"\vRunWorkload\x12\x19.ateom.RunWorkloadRequest\x1a\x1a.ateom.RunWorkloadResponse\"\x00\x12[\n" +
	"\x12CheckpointWorkload\x12 .ateom.CheckpointWorkloadRequest\x1a!.ateom.CheckpointWorkloadResponse\"\x00\x12R\n" +
	"\x0fRestoreWorkload\x12\x1d.ateom.RestoreWorkloadRequest\x1a\x1e.ateom.RestoreWorkloadResponse\"\x00\x12U\n" +
	"\x10GetWorkloadStats\x12\x1e.ateom.GetWorkloadStatsRequest\x1a\x1f.ateom.GetWorkloadStatsResponse\"\x00\x12g\n" +
	"\x16GetActiveWorkloadStats\x12$.ateom.GetActiveWorkloadStatsRequest\x1a%.ateom.GetActiveWorkloadStatsResponse\"\x00\x12X\n" +
	"\x11TerminateWorkload\x12\x1f.ateom.TerminateWorkloadRequest\x1a .ateom.TerminateWorkloadResponse\"\x00B=Z;github.com/agent-substrate/substrate/internal/proto/ateompbb\x06proto3"

var (
	file_ateom_proto_rawDescOnce sync.Once
	file_ateom_proto_rawDescData []byte
)

func file_ateom_proto_rawDescGZIP() []byte {
	file_ateom_proto_rawDescOnce.Do(func() {
		file_ateom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateom_proto_rawDesc), len(file_ateom_proto_rawDesc)))
	})
	return file_ateom_proto_rawDescData
}

var file_ateom_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ateom_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_ateom_proto_goTypes = []any{
	(SnapshotScope)(0),                     // 0: ateom.SnapshotScope
	(SandboxClass)(0),                      // 1: ateom.SandboxClass
	(StatsSource)(0),                       // 2: ateom.StatsSource
	(*ActorDirs)(nil),                      // 3: ateom.ActorDirs
	(*TerminateWorkloadRequest)(nil),       // 4: ateom.TerminateWorkloadRequest
	(*TerminateWorkloadResponse)(nil),      // 5: ateom.TerminateWorkloadResponse
	(*RunWorkloadRequest)(nil),             // 6: ateom.RunWorkloadRequest
	(*EgressGateway)(nil),                  // 7: ateom.EgressGateway
	(*WorkloadSpec)(nil),                   // 8: ateom.WorkloadSpec
	(*Container)(nil),                      // 9: ateom.Container
	(*VolumeMount)(nil),                    // 10: ateom.VolumeMount
	(*DurableDirVolumeMount)(nil),          // 11: ateom.DurableDirVolumeMount
	(*SystemInfoVolumeMount)(nil),          // 12: ateom.SystemInfoVolumeMount
	(*ImageVolumeMount)(nil),               // 13: ateom.ImageVolumeMount
	(*WakeupProbe)(nil),                    // 14: ateom.WakeupProbe
	(*HTTPGetAction)(nil),                  // 15: ateom.HTTPGetAction
	(*RunWorkloadResponse)(nil),            // 16: ateom.RunWorkloadResponse
	(*CheckpointWorkloadRequest)(nil),      // 17: ateom.CheckpointWorkloadRequest
	(*CheckpointWorkloadResponse)(nil),     // 18: ateom.CheckpointWorkloadResponse
	(*RestoreWorkloadRequest)(nil),         // 19: ateom.RestoreWorkloadRequest
	(*RestoreWorkloadResponse)(nil),        // 20: ateom.RestoreWorkloadResponse
	(*GetWorkloadStatsRequest)(nil),        // 21: ateom.GetWorkloadStatsRequest
	(*WorkloadStatsSample)(nil),            // 22: ateom.WorkloadStatsSample
	(*GetWorkloadStatsResponse)(nil),       // 23: ateom.GetWorkloadStatsResponse
	(*GetActiveWorkloadStatsRequest)(nil),  // 24: ateom.GetActiveWorkloadStatsRequest
	(*GetActiveWorkloadStatsResponse)(nil), // 25: ateom.GetActiveWorkloadStatsResponse
	nil,                                    // 26: ateom.RunWorkloadRequest.RuntimeAssetPathsEntry
	nil,                                    // 27: ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntry
	nil,                                    // 28: ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntry
}
var file_ateom_proto_depIdxs = []int32{
	8,  // 0: ateom.TerminateWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	3,  // 1: ateom.TerminateWorkloadRequest.actor_dirs:type_name -> ateom.ActorDirs
	8,  // 2: ateom.RunWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	26, // 3: ateom.RunWorkloadRequest.runtime_asset_paths:type_name -> ateom.RunWorkloadRequest.RuntimeAssetPathsEntry
	7,  // 4: ateom.RunWorkloadRequest.egress_gateway:type_name -> ateom.EgressGateway
	3,  // 5: ateom.RunWorkloadRequest.actor_dirs:type_name -> ateom.ActorDirs
	9,  // 6: ateom.WorkloadSpec.containers:type_name -> ateom.Container
	14, // 7: ateom.Container.wakeup_probe:type_name -> ateom.WakeupProbe
	11, // 8: ateom.Container.durable_dir_volume_mounts:type_name -> ateom.DurableDirVolumeMount
	10, // 9: ateom.Container.csi_volume_mounts:type_name -> ateom.VolumeMount
	12, // 10: ateom.Container.system_info_volume_mounts:type_name -> ateom.SystemInfoVolumeMount
	13, // 11: ateom.Container.image_volume_mounts:type_name -> ateom.ImageVolumeMount
	15, // 12: ateom.WakeupProbe.http_get:type_name -> ateom.HTTPGetAction
	8,  // 13: ateom.CheckpointWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	27, // 14: ateom.CheckpointWorkloadRequest.runtime_asset_paths:type_name -> ateom.CheckpointWorkloadRequest.RuntimeAssetPathsEntry
	0,  // 15: ateom.CheckpointWorkloadRequest.scope:type_name -> ateom.SnapshotScope
	3,  // 16: ateom.CheckpointWorkloadRequest.actor_dirs:type_name -> ateom.ActorDirs
	8,  // 17: ateom.RestoreWorkloadRequest.spec:type_name -> ateom.WorkloadSpec
	28, // 18: ateom.RestoreWorkloadRequest.runtime_asset_paths:type_name -> ateom.RestoreWorkloadRequest.RuntimeAssetPathsEntry
	0,  // 19: ateom.RestoreWorkloadRequest.scope:type_name -> ateom.SnapshotScope
	7,  // 20: ateom.RestoreWorkloadRequest.egress_gateway:type_name -> ateom.EgressGateway
	3,  // 21: ateom.RestoreWorkloadRequest.actor_dirs:type_name -> ateom.ActorDirs
	1,  // 22: ateom.WorkloadStatsSample.sandbox_class:type_name -> ateom.SandboxClass
	2,  // 23: ateom.WorkloadStatsSample.source:type_name -> ateom.StatsSource
	22, // 24: ateom.GetWorkloadStatsResponse.sample:type_name -> ateom.WorkloadStatsSample
	22, // 25: ateom.GetActiveWorkloadStatsResponse.samples:type_name -> ateom.WorkloadStatsSample
	6,  // 26: ateom.Ateom.RunWorkload:input_type -> ateom.RunWorkloadRequest
	17, // 27: ateom.Ateom.CheckpointWorkload:input_type -> ateom.CheckpointWorkloadRequest
	19, // 28: ateom.Ateom.RestoreWorkload:input_type -> ateom.RestoreWorkloadRequest
	21, // 29: ateom.Ateom.GetWorkloadStats:input_type -> ateom.GetWorkloadStatsRequest
	24, // 30: ateom.Ateom.GetActiveWorkloadStats:input_type -> ateom.GetActiveWorkloadStatsRequest
	4,  // 31: ateom.Ateom.TerminateWorkload:input_type -> ateom.TerminateWorkloadRequest
	16, // 32: ateom.Ateom.RunWorkload:output_type -> ateom.RunWorkloadResponse
	18, // 33: ateom.Ateom.CheckpointWorkload:output_type -> ateom.CheckpointWorkloadResponse
	20, // 34: ateom.Ateom.RestoreWorkload:output_type -> ateom.RestoreWorkloadResponse
	23, // 35: ateom.Ateom.GetWorkloadStats:output_type -> ateom.GetWorkloadStatsResponse
	25, // 36: ateom.Ateom.GetActiveWorkloadStats:output_type -> ateom.GetActiveWorkloadStatsResponse
	5,  // 37: ateom.Ateom.TerminateWorkload:output_type -> ateom.TerminateWorkloadResponse
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_ateom_proto_init() }
func file_ateom_proto_init() {
	if File_ateom_proto != nil {
		return
	}
	file_ateom_proto_msgTypes[3].OneofWrappers = []any{}
	file_ateom_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateom_proto_rawDesc), len(file_ateom_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ateom_proto_goTypes,
		DependencyIndexes: file_ateom_proto_depIdxs,
		EnumInfos:         file_ateom_proto_enumTypes,
		MessageInfos:      file_ateom_proto_msgTypes,
	}.Build()
	File_ateom_proto = out.File
	file_ateom_proto_goTypes = nil
	file_ateom_proto_depIdxs = nil
}
