// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: credprovider.proto

package credproviderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchSecretRequest asks a provider to resolve one credential URI.
type FetchSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The uri for the substrate secret to fetch.
	// Example: ate-secret://<provider name>/<provider tail>
	// The provider tail is provider-interpreted.
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// The SPIFFE ID of the actor on whose behalf the secret is fetched, as
	// verified by the egress gateway. This field always contains a SPIFFE ID.
	ActorSpiffeId string `protobuf:"bytes,2,opt,name=actor_spiffe_id,json=actorSpiffeId,proto3" json:"actor_spiffe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSecretRequest) Reset() {
	*x = FetchSecretRequest{}
	mi := &file_credprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSecretRequest) ProtoMessage() {}

func (x *FetchSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSecretRequest.ProtoReflect.Descriptor instead.
func (*FetchSecretRequest) Descriptor() ([]byte, []int) {
	return file_credprovider_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSecretRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FetchSecretRequest) GetActorSpiffeId() string {
	if x != nil {
		return x.ActorSpiffeId
	}
	return ""
}

// FetchSecretResponse carries the resolved credential.
type FetchSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw bytes contains the secret.
	OpaqueBytes   []byte `protobuf:"bytes,1,opt,name=opaque_bytes,json=opaqueBytes,proto3" json:"opaque_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSecretResponse) Reset() {
	*x = FetchSecretResponse{}
	mi := &file_credprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSecretResponse) ProtoMessage() {}

func (x *FetchSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSecretResponse.ProtoReflect.Descriptor instead.
func (*FetchSecretResponse) Descriptor() ([]byte, []int) {
	return file_credprovider_proto_rawDescGZIP(), []int{1}
}

func (x *FetchSecretResponse) GetOpaqueBytes() []byte {
	if x != nil {
		return x.OpaqueBytes
	}
	return nil
}

var File_credprovider_proto protoreflect.FileDescriptor

const file_credprovider_proto_rawDesc = "" +
	"\n" +
	"\x12credprovider.proto\x12\fcredprovider\"N\n" +
	"\x12FetchSecretRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12&\n" +
	"\x0factor_spiffe_id\x18\x02 \x01(\tR\ractorSpiffeId\"=\n" +
	"\x13FetchSecretResponse\x12&\n" +
	"\fopaque_bytes\x18\x01 \x01(\fB\x03\x80\x01\x01R\vopaqueBytes2j\n" +
	"\x12CredentialProvider\x12T\n" +
	"\vFetchSecret\x12 .credprovider.FetchSecretRequest\x1a!.credprovider.FetchSecretResponse\"\x00B?Z=github.com/agent-substrate/substrate/pkg/proto/credproviderpbb\x06proto3"

var (
	file_credprovider_proto_rawDescOnce sync.Once
	file_credprovider_proto_rawDescData []byte
)

func file_credprovider_proto_rawDescGZIP() []byte {
	file_credprovider_proto_rawDescOnce.Do(func() {
		file_credprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credprovider_proto_rawDesc), len(file_credprovider_proto_rawDesc)))
	})
	return file_credprovider_proto_rawDescData
}

var file_credprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_credprovider_proto_goTypes = []any{
	(*FetchSecretRequest)(nil),  // 0: credprovider.FetchSecretRequest
	(*FetchSecretResponse)(nil), // 1: credprovider.FetchSecretResponse
}
var file_credprovider_proto_depIdxs = []int32{
	0, // 0: credprovider.CredentialProvider.FetchSecret:input_type -> credprovider.FetchSecretRequest
	1, // 1: credprovider.CredentialProvider.FetchSecret:output_type -> credprovider.FetchSecretResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credprovider_proto_init() }
func file_credprovider_proto_init() {
	if File_credprovider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credprovider_proto_rawDesc), len(file_credprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credprovider_proto_goTypes,
		DependencyIndexes: file_credprovider_proto_depIdxs,
		MessageInfos:      file_credprovider_proto_msgTypes,
	}.Build()
	File_credprovider_proto = out.File
	file_credprovider_proto_goTypes = nil
	file_credprovider_proto_depIdxs = nil
}
