// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build linux

package atunnel

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"strconv"
	"unsafe"

	"golang.org/x/sys/unix"
)

// IP6T_SO_ORIGINAL_DST is not generated by golang.org/x/sys/unix. It is
// defined as 80 in linux/netfilter_ipv6/ip6_tables.h.
const ip6tSOOriginalDst = 80

// TCPOriginalDestination reads the IPv4 or IPv6 destination preserved by a
// Linux REDIRECT rule.
func TCPOriginalDestination(conn net.Conn) (string, error) {
	tcpConn, ok := conn.(*net.TCPConn)
	if !ok {
		return "", fmt.Errorf("atunnel: original destination requires a TCP connection, got %T", conn)
	}
	rawConn, err := tcpConn.SyscallConn()
	if err != nil {
		return "", fmt.Errorf("atunnel: acquiring TCP syscall connection: %w", err)
	}

	var sockoptErr error
	var destination string
	if err := rawConn.Control(func(fd uintptr) {
		destination, sockoptErr = originalIPv4Destination(fd)
		// Linux returns ENOENT when the IPv4 original-destination option is
		// queried on a redirected IPv6 connection. Only then try the IPv6
		// equivalent, so unrelated IPv4 failures retain their original error.
		if errors.Is(sockoptErr, unix.ENOENT) {
			destination, sockoptErr = originalIPv6Destination(fd)
		}
	}); err != nil {
		return "", fmt.Errorf("atunnel: accessing TCP socket: %w", err)
	}
	if sockoptErr != nil {
		return "", fmt.Errorf("atunnel: reading original TCP destination: %w", sockoptErr)
	}
	return destination, nil
}

func originalIPv4Destination(fd uintptr) (string, error) {
	var addr unix.RawSockaddrInet4
	if errno := getOriginalDestination(fd, unix.SOL_IP, unix.SO_ORIGINAL_DST, unsafe.Pointer(&addr), unsafe.Sizeof(addr)); errno != 0 {
		return "", errno
	}
	return formatOriginalDestination(addr.Addr[:], addr.Port)
}

func originalIPv6Destination(fd uintptr) (string, error) {
	var addr unix.RawSockaddrInet6
	if errno := getOriginalDestination(fd, unix.SOL_IPV6, ip6tSOOriginalDst, unsafe.Pointer(&addr), unsafe.Sizeof(addr)); errno != 0 {
		return "", errno
	}
	return formatOriginalDestination(addr.Addr[:], addr.Port)
}

func getOriginalDestination(fd uintptr, level, option int, addr unsafe.Pointer, addrSize uintptr) unix.Errno {
	size := uint32(addrSize)
	_, _, errno := unix.Syscall6(
		unix.SYS_GETSOCKOPT,
		fd,
		uintptr(level),
		uintptr(option),
		uintptr(addr),
		uintptr(unsafe.Pointer(&size)),
		0,
	)
	return errno
}

func formatOriginalDestination(ip []byte, rawPort uint16) (string, error) {
	portBytes := (*[2]byte)(unsafe.Pointer(&rawPort))
	port := binary.BigEndian.Uint16(portBytes[:])
	if port == 0 {
		return "", fmt.Errorf("atunnel: original TCP destination has port zero")
	}
	return net.JoinHostPort(net.IP(ip).String(), strconv.Itoa(int(port))), nil
}
