//go:build linux

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// System-info volume support for the micro-VM runtime.
//
// A system-info volume is a read-only directory of files generated by atelet
// on the host on every Run/Restore (e.g. the actorMetadata data-source files),
// so its contents always describe the actor actually being started, whatever
// checkpointed state it boots from. The host side is owned by atelet, which
// creates one directory per volume under
// ateompath.SystemInfoVolumeRootsDir(actorUID) and wipes/rebuilds them when
// the actor's directories are reset.
//
// ateom exposes that host directory to the guest under the single kataShared
// virtio-fs share at SharedDir(actorUID)/system-info (in-guest path:
// kata.GuestSystemInfoVolumeDir(volume)), like durable-dir and CSI volumes —
// no extra virtio-fs device. Read-only is enforced twice: the host bind is
// remounted read-only (so nothing in the guest can write through the share),
// and each container bind adds "ro" (so the workload can't write the mount).
//
// Unlike durable-dir volumes, system-info volumes are deliberately absent
// from the checkpoint path: their contents must never be captured into
// snapshots (see the SystemInfo semantics in docs/api-guide.md). Regeneration
// is safe under find-paths migration because atelet rewrites the files at
// their stable share-relative paths before the share's virtiofsd starts.

package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/agent-substrate/substrate/cmd/ateom-microvm/internal/kata"
	"github.com/agent-substrate/substrate/cmd/ateom-microvm/internal/reaper"
	"github.com/agent-substrate/substrate/internal/ateompath"
	"github.com/agent-substrate/substrate/internal/proto/ateompb"
	specs "github.com/opencontainers/runtime-spec/specs-go"
)

// hasSystemInfoVolumes reports whether any container mounts a system-info
// volume.
func hasSystemInfoVolumes(containers []*ateompb.Container) bool {
	for _, c := range containers {
		if len(c.GetSystemInfoVolumeMounts()) > 0 {
			return true
		}
	}
	return false
}

// systemInfoMounts returns the OCI mounts that expose a container's
// system-info volumes at the paths it declared, read-only. Each source is that
// volume's directory inside the guest's shared tree, which the agent mounts at
// sandbox creation.
func systemInfoMounts(mounts []*ateompb.SystemInfoVolumeMount) []specs.Mount {
	out := make([]specs.Mount, 0, len(mounts))
	for _, m := range mounts {
		out = append(out, specs.Mount{
			Destination: m.GetMountPath(),
			Source:      kata.GuestSystemInfoVolumeDir(m.GetVolumeName()),
			Type:        "bind",
			Options:     []string{"rbind", "ro"},
		})
	}
	return out
}

// stageSystemInfoVolumes bind-mounts the actor's host system-info directory
// into the sandbox's shared virtio-fs tree at SharedDir(actorUID)/system-info,
// then remounts the bind read-only: atelet is the only writer, and it writes
// the host source directly, never through the share.
func (s *AteomService) stageSystemInfoVolumes(ctx context.Context, actorUID string) error {
	src := ateompath.SystemInfoVolumeRootsDir(actorUID)
	if _, err := os.Stat(src); err != nil {
		return fmt.Errorf("while checking system-info volumes dir %q: %w", src, err)
	}
	dst := filepath.Join(kata.SharedDir(actorUID), "system-info")
	// Drop any stale mount first (lazy if busy), then ensure clean mountpoint.
	if err := reaper.Run(exec.Command("umount", dst)); err != nil {
		_ = reaper.Run(exec.Command("umount", "-l", dst))
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating %q: %w", dst, err)
	}
	cmd := exec.CommandContext(ctx, "mount", "--bind", src, dst)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	if err := reaper.Run(cmd); err != nil {
		return fmt.Errorf("bind-mounting system-info volumes at %q: %w (%s)", dst, err, strings.TrimSpace(stderr.String()))
	}
	ro := exec.CommandContext(ctx, "mount", "-o", "remount,bind,ro", dst)
	var roErr strings.Builder
	ro.Stderr = &roErr
	if err := reaper.Run(ro); err != nil {
		return fmt.Errorf("remounting system-info volumes read-only %q: %w (%s)", dst, err, strings.TrimSpace(roErr.String()))
	}
	return nil
}
