// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: grpcecho.proto

package grpcechopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Echo_Echo_FullMethodName       = "/grpcecho.Echo/Echo"
	Echo_EchoStream_FullMethodName = "/grpcecho.Echo/EchoStream"
	Echo_EchoBidi_FullMethodName   = "/grpcecho.Echo/EchoBidi"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Echo is the smallest service that can prove a gRPC request and its response
// crossed a network path intact. It exists for the egress e2e coverage: the
// origin is internal/e2e/fixtures/testserver (its grpc subcommand) and the
// client is the egress demo actor, which reaches it through the egress gateway's
// CONNECT tunnel.
//
// One method per streaming shape, because they fail differently. A unary
// response carries its status in trailers sent immediately after the message; a
// server-stream holds the connection open across many frames; a bidirectional
// stream has both directions carrying frames at once and then half-closes one
// of them. A path that buffers, downgrades to HTTP/1.1, serializes the two
// directions, or reaps an idle tunnel breaks one of these without touching the
// others.
type EchoClient interface {
	// Echo returns the message it was sent.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// EchoStream returns the message it was sent count times, one response per
	// message, each numbered with its position in the stream.
	EchoStream(ctx context.Context, in *EchoStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
	// EchoBidi answers every request with one response, as each request arrives,
	// numbered with its position in the stream. The caller decides how many to
	// send and half-closes when it is done.
	//
	// Unlike EchoStream, the server must not wait for the client to finish: a
	// caller that sends its next request only after reading the previous response
	// deadlocks against an implementation -- or a relay -- that reads the request
	// direction to exhaustion before writing anything back.
	EchoBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoStream(ctx context.Context, in *EchoStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], Echo_EchoStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoStreamRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamClient = grpc.ServerStreamingClient[EchoResponse]

func (c *echoClient) EchoBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], Echo_EchoBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoBidiClient = grpc.BidiStreamingClient[EchoRequest, EchoResponse]

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility.
//
// Echo is the smallest service that can prove a gRPC request and its response
// crossed a network path intact. It exists for the egress e2e coverage: the
// origin is internal/e2e/fixtures/testserver (its grpc subcommand) and the
// client is the egress demo actor, which reaches it through the egress gateway's
// CONNECT tunnel.
//
// One method per streaming shape, because they fail differently. A unary
// response carries its status in trailers sent immediately after the message; a
// server-stream holds the connection open across many frames; a bidirectional
// stream has both directions carrying frames at once and then half-closes one
// of them. A path that buffers, downgrades to HTTP/1.1, serializes the two
// directions, or reaps an idle tunnel breaks one of these without touching the
// others.
type EchoServer interface {
	// Echo returns the message it was sent.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// EchoStream returns the message it was sent count times, one response per
	// message, each numbered with its position in the stream.
	EchoStream(*EchoStreamRequest, grpc.ServerStreamingServer[EchoResponse]) error
	// EchoBidi answers every request with one response, as each request arrives,
	// numbered with its position in the stream. The caller decides how many to
	// send and half-closes when it is done.
	//
	// Unlike EchoStream, the server must not wait for the client to finish: a
	// caller that sends its next request only after reading the previous response
	// deadlocks against an implementation -- or a relay -- that reads the request
	// direction to exhaustion before writing anything back.
	EchoBidi(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServer struct{}

func (UnimplementedEchoServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoServer) EchoStream(*EchoStreamRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method EchoStream not implemented")
}
func (UnimplementedEchoServer) EchoBidi(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method EchoBidi not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}
func (UnimplementedEchoServer) testEmbeddedByValue()              {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	// If the following call panics, it indicates UnimplementedEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).EchoStream(m, &grpc.GenericServerStream[EchoStreamRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamServer = grpc.ServerStreamingServer[EchoResponse]

func _Echo_EchoBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).EchoBidi(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoBidiServer = grpc.BidiStreamingServer[EchoRequest, EchoResponse]

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcecho.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoStream",
			Handler:       _Echo_EchoStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EchoBidi",
			Handler:       _Echo_EchoBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcecho.proto",
}
