// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: atelet.proto

package ateletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeType int32

const (
	VolumeType_VOLUME_TYPE_UNSPECIFIED VolumeType = 0
	VolumeType_VOLUME_TYPE_DURABLE_DIR VolumeType = 1
	VolumeType_VOLUME_TYPE_EXTERNAL    VolumeType = 2
)

// Enum value maps for VolumeType.
var (
	VolumeType_name = map[int32]string{
		0: "VOLUME_TYPE_UNSPECIFIED",
		1: "VOLUME_TYPE_DURABLE_DIR",
		2: "VOLUME_TYPE_EXTERNAL",
	}
	VolumeType_value = map[string]int32{
		"VOLUME_TYPE_UNSPECIFIED": 0,
		"VOLUME_TYPE_DURABLE_DIR": 1,
		"VOLUME_TYPE_EXTERNAL":    2,
	}
)

func (x VolumeType) Enum() *VolumeType {
	p := new(VolumeType)
	*p = x
	return p
}

func (x VolumeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeType) Descriptor() protoreflect.EnumDescriptor {
	return file_atelet_proto_enumTypes[0].Descriptor()
}

func (VolumeType) Type() protoreflect.EnumType {
	return &file_atelet_proto_enumTypes[0]
}

func (x VolumeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeType.Descriptor instead.
func (VolumeType) EnumDescriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{0}
}

type CheckpointType int32

const (
	// Should never happen
	CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED CheckpointType = 0
	// Save snapshot only in local filesystem
	CheckpointType_CHECKPOINT_TYPE_LOCAL CheckpointType = 1
	// Save snapshot to object storage
	CheckpointType_CHECKPOINT_TYPE_EXTERNAL CheckpointType = 2
)

// Enum value maps for CheckpointType.
var (
	CheckpointType_name = map[int32]string{
		0: "CHECKPOINT_TYPE_UNSPECIFIED",
		1: "CHECKPOINT_TYPE_LOCAL",
		2: "CHECKPOINT_TYPE_EXTERNAL",
	}
	CheckpointType_value = map[string]int32{
		"CHECKPOINT_TYPE_UNSPECIFIED": 0,
		"CHECKPOINT_TYPE_LOCAL":       1,
		"CHECKPOINT_TYPE_EXTERNAL":    2,
	}
)

func (x CheckpointType) Enum() *CheckpointType {
	p := new(CheckpointType)
	*p = x
	return p
}

func (x CheckpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_atelet_proto_enumTypes[1].Descriptor()
}

func (CheckpointType) Type() protoreflect.EnumType {
	return &file_atelet_proto_enumTypes[1]
}

func (x CheckpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointType.Descriptor instead.
func (CheckpointType) EnumDescriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{1}
}

type SnapshotScope int32

const (
	// Not valid option; should never happen.
	SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED SnapshotScope = 0
	// Capture process memory plus the full filesystem delta on top of the OCI
	// image (including any attached DurableDir volumes).
	SnapshotScope_SNAPSHOT_SCOPE_FULL SnapshotScope = 1
	// Capture only the contents of attached volumes that support snapshots
	// (currently DurableDir-typed volumes). Memory and the rest of rootfs are
	// excluded.
	SnapshotScope_SNAPSHOT_SCOPE_DATA SnapshotScope = 2
	// Restore-only: restore the ActorTemplate's golden snapshot's guest state
	// (memory + full filesystem delta) combined with the snapshot's durable
	// data. Never valid for Checkpoint — snapshots only ever capture FULL or
	// DATA; whether a snapshot restores from its own content or on the golden
	// is decided by the control plane from the template's onResume
	// configuration.
	SnapshotScope_SNAPSHOT_SCOPE_DATA_ON_GOLDEN SnapshotScope = 3
)

// Enum value maps for SnapshotScope.
var (
	SnapshotScope_name = map[int32]string{
		0: "SNAPSHOT_SCOPE_UNSPECIFIED",
		1: "SNAPSHOT_SCOPE_FULL",
		2: "SNAPSHOT_SCOPE_DATA",
		3: "SNAPSHOT_SCOPE_DATA_ON_GOLDEN",
	}
	SnapshotScope_value = map[string]int32{
		"SNAPSHOT_SCOPE_UNSPECIFIED":    0,
		"SNAPSHOT_SCOPE_FULL":           1,
		"SNAPSHOT_SCOPE_DATA":           2,
		"SNAPSHOT_SCOPE_DATA_ON_GOLDEN": 3,
	}
)

func (x SnapshotScope) Enum() *SnapshotScope {
	p := new(SnapshotScope)
	*p = x
	return p
}

func (x SnapshotScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotScope) Descriptor() protoreflect.EnumDescriptor {
	return file_atelet_proto_enumTypes[2].Descriptor()
}

func (SnapshotScope) Type() protoreflect.EnumType {
	return &file_atelet_proto_enumTypes[2]
}

func (x SnapshotScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotScope.Descriptor instead.
func (SnapshotScope) EnumDescriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{2}
}

type RunRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	Atespace               string                 `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName              string                 `protobuf:"bytes,3,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid               string                 `protobuf:"bytes,4,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,5,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,6,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// The sandbox binaries to use for booting this actor from scratch. atelet
	// fetches the relevant assets and records them with the actor's on-node state
	// so a later Checkpoint can pin the same version into the snapshot manifest.
	SandboxAssets *SandboxAssets `protobuf:"bytes,8,opt,name=sandbox_assets,json=sandboxAssets,proto3" json:"sandbox_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_atelet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *RunRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RunRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RunRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RunRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RunRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RunRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RunRequest) GetSandboxAssets() *SandboxAssets {
	if x != nil {
		return x.SandboxAssets
	}
	return nil
}

// AssetFile is one content-addressed file atelet fetches for a sandbox runtime
// (e.g. the gVisor release tarball).
type AssetFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gs:// URL to download the asset from.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Lower-case hex SHA256; names the cached file and verifies its integrity.
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetFile) Reset() {
	*x = AssetFile{}
	mi := &file_atelet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFile) ProtoMessage() {}

func (x *AssetFile) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetFile.ProtoReflect.Descriptor instead.
func (*AssetFile) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{1}
}

func (x *AssetFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AssetFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// ArchAssets is the set of assets for a single architecture, keyed by asset
// name (a wrapper message because proto map values cannot themselves be maps).
type ArchAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string]*AssetFile  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // asset name -> file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchAssets) Reset() {
	*x = ArchAssets{}
	mi := &file_atelet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchAssets) ProtoMessage() {}

func (x *ArchAssets) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchAssets.ProtoReflect.Descriptor instead.
func (*ArchAssets) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{2}
}

func (x *ArchAssets) GetFiles() map[string]*AssetFile {
	if x != nil {
		return x.Files
	}
	return nil
}

// SandboxAssets is the generic, backend-agnostic description of the sandbox
// binaries for an actor: a sandbox class plus assets keyed first by
// architecture (GOARCH) and then by asset name. atelet's backend code
// interprets the asset names (gVisor expects "gvisor", the release tarball;
// legacy "runsc", a bare binary, is still accepted).
type SandboxAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxClass  string                 `protobuf:"bytes,1,opt,name=sandbox_class,json=sandboxClass,proto3" json:"sandbox_class,omitempty"`                                           // e.g. "gvisor"
	Assets        map[string]*ArchAssets `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arch -> {name -> file}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxAssets) Reset() {
	*x = SandboxAssets{}
	mi := &file_atelet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxAssets) ProtoMessage() {}

func (x *SandboxAssets) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxAssets.ProtoReflect.Descriptor instead.
func (*SandboxAssets) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxAssets) GetSandboxClass() string {
	if x != nil {
		return x.SandboxClass
	}
	return ""
}

func (x *SandboxAssets) GetAssets() map[string]*ArchAssets {
	if x != nil {
		return x.Assets
	}
	return nil
}

// WorkloadSpec parallels Pod, but with far fewer configurable fields.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	PauseImage    string                 `protobuf:"bytes,2,opt,name=pause_image,json=pauseImage,proto3" json:"pause_image,omitempty"`
	Volumes       []*Volume              `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_atelet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *WorkloadSpec) GetPauseImage() string {
	if x != nil {
		return x.PauseImage
	}
	return ""
}

func (x *WorkloadSpec) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type DurableDirVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurableDirVolume) Reset() {
	*x = DurableDirVolume{}
	mi := &file_atelet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurableDirVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurableDirVolume) ProtoMessage() {}

func (x *DurableDirVolume) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurableDirVolume.ProtoReflect.Descriptor instead.
func (*DurableDirVolume) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{5}
}

type ExternalVolumeSource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StorageVolumeId string                 `protobuf:"bytes,1,opt,name=storage_volume_id,json=storageVolumeId,proto3" json:"storage_volume_id,omitempty"`
	VolumeType      string                 `protobuf:"bytes,2,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExternalVolumeSource) Reset() {
	*x = ExternalVolumeSource{}
	mi := &file_atelet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalVolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalVolumeSource) ProtoMessage() {}

func (x *ExternalVolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalVolumeSource.ProtoReflect.Descriptor instead.
func (*ExternalVolumeSource) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalVolumeSource) GetStorageVolumeId() string {
	if x != nil {
		return x.StorageVolumeId
	}
	return ""
}

func (x *ExternalVolumeSource) GetVolumeType() string {
	if x != nil {
		return x.VolumeType
	}
	return ""
}

type Volume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  VolumeType             `protobuf:"varint,2,opt,name=type,proto3,enum=atelet.VolumeType" json:"type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Volume_DurableDir
	//	*Volume_External
	Source        isVolume_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_atelet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{7}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetType() VolumeType {
	if x != nil {
		return x.Type
	}
	return VolumeType_VOLUME_TYPE_UNSPECIFIED
}

func (x *Volume) GetSource() isVolume_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Volume) GetDurableDir() *DurableDirVolume {
	if x != nil {
		if x, ok := x.Source.(*Volume_DurableDir); ok {
			return x.DurableDir
		}
	}
	return nil
}

func (x *Volume) GetExternal() *ExternalVolumeSource {
	if x != nil {
		if x, ok := x.Source.(*Volume_External); ok {
			return x.External
		}
	}
	return nil
}

type isVolume_Source interface {
	isVolume_Source()
}

type Volume_DurableDir struct {
	DurableDir *DurableDirVolume `protobuf:"bytes,3,opt,name=durable_dir,json=durableDir,proto3,oneof"`
}

type Volume_External struct {
	External *ExternalVolumeSource `protobuf:"bytes,4,opt,name=external,proto3,oneof"`
}

func (*Volume_DurableDir) isVolume_Source() {}

func (*Volume_External) isVolume_Source() {}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_atelet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{8}
}

func (x *VolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	Env           []*EnvEntry            `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Readyz        *Readyz                `protobuf:"bytes,5,opt,name=readyz,proto3" json:"readyz,omitempty"`
	VolumeMounts  []*VolumeMount         `protobuf:"bytes,6,rep,name=volume_mounts,json=volumeMounts,proto3" json:"volume_mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_atelet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{9}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Container) GetEnv() []*EnvEntry {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetReadyz() *Readyz {
	if x != nil {
		return x.Readyz
	}
	return nil
}

func (x *Container) GetVolumeMounts() []*VolumeMount {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

type EnvEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvEntry) Reset() {
	*x = EnvEntry{}
	mi := &file_atelet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvEntry) ProtoMessage() {}

func (x *EnvEntry) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvEntry.ProtoReflect.Descriptor instead.
func (*EnvEntry) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{10}
}

func (x *EnvEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Readyz describes how to check that a container is ready to serve.
// Only HTTP is supported today.
type Readyz struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	HttpGet *HTTPGetAction         `protobuf:"bytes,1,opt,name=http_get,json=httpGet,proto3" json:"http_get,omitempty"`
	// How long to keep polling before giving up and failing the actor start.
	// Zero means the ateom's default.
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Readyz) Reset() {
	*x = Readyz{}
	mi := &file_atelet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Readyz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Readyz) ProtoMessage() {}

func (x *Readyz) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Readyz.ProtoReflect.Descriptor instead.
func (*Readyz) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{11}
}

func (x *Readyz) GetHttpGet() *HTTPGetAction {
	if x != nil {
		return x.HttpGet
	}
	return nil
}

func (x *Readyz) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// HTTPGetAction performs an HTTP GET against the container.
type HTTPGetAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to access on the HTTP server. Empty means "/readyz".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// TCP port to connect to (1..65535).
	Port          int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPGetAction) Reset() {
	*x = HTTPGetAction{}
	mi := &file_atelet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPGetAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPGetAction) ProtoMessage() {}

func (x *HTTPGetAction) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPGetAction.ProtoReflect.Descriptor instead.
func (*HTTPGetAction) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{12}
}

func (x *HTTPGetAction) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPGetAction) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_atelet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{13}
}

type LocalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A sub-directory on the local filesystem below which the checkpoint data will be
	// stored.  The structure of the checkpoint should generally be treated as opaque.
	SnapshotPrefix string `protobuf:"bytes,1,opt,name=snapshot_prefix,json=snapshotPrefix,proto3" json:"snapshot_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalCheckpointConfiguration) Reset() {
	*x = LocalCheckpointConfiguration{}
	mi := &file_atelet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCheckpointConfiguration) ProtoMessage() {}

func (x *LocalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*LocalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{14}
}

func (x *LocalCheckpointConfiguration) GetSnapshotPrefix() string {
	if x != nil {
		return x.SnapshotPrefix
	}
	return ""
}

type ExternalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An object storage URI prefix below which the checkpoint data will be
	// stored.
	//
	// The structure of the checkpoint should generally be treated as opaque. For
	// gVisor, the checkpoint consists of a checkpoint.img file that contains the
	// memory, sentry state, and filesystem deltas.  ateom will write additional
	// files to store the WorkloadSpec, which must be reassembled before gVisor
	// can restore a checkpoint.
	//
	// For example: "gs://bucket/actors/1234/snapshots/5678/"
	SnapshotUriPrefix string `protobuf:"bytes,1,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalCheckpointConfiguration) Reset() {
	*x = ExternalCheckpointConfiguration{}
	mi := &file_atelet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCheckpointConfiguration) ProtoMessage() {}

func (x *ExternalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*ExternalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{15}
}

func (x *ExternalCheckpointConfiguration) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

type CheckpointRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	Atespace               string                 `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName              string                 `protobuf:"bytes,3,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid               string                 `protobuf:"bytes,4,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,5,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,6,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	// Sandbox binary config is not sent on checkpoint: atelet uses the version the
	// actor is currently running (recorded with the actor's on-node state at
	// Run/Restore) and records it into the snapshot manifest.
	Spec *WorkloadSpec  `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type CheckpointType `protobuf:"varint,8,opt,name=type,proto3,enum=atelet.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*CheckpointRequest_LocalConfig
	//	*CheckpointRequest_ExternalConfig
	Config isCheckpointRequest_Config `protobuf_oneof:"config"`
	// What should be included in the checkpoint.
	Scope         SnapshotScope `protobuf:"varint,11,opt,name=scope,proto3,enum=atelet.SnapshotScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_atelet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{16}
}

func (x *CheckpointRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *CheckpointRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *CheckpointRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *CheckpointRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CheckpointRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CheckpointRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *CheckpointRequest) GetConfig() isCheckpointRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CheckpointRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *CheckpointRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

func (x *CheckpointRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

type isCheckpointRequest_Config interface {
	isCheckpointRequest_Config()
}

type CheckpointRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,9,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type CheckpointRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,10,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*CheckpointRequest_LocalConfig) isCheckpointRequest_Config() {}

func (*CheckpointRequest_ExternalConfig) isCheckpointRequest_Config() {}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_atelet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{17}
}

type RestoreRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	Atespace               string                 `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	ActorName              string                 `protobuf:"bytes,3,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorUid               string                 `protobuf:"bytes,4,opt,name=actor_uid,json=actorUid,proto3" json:"actor_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,5,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,6,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	// Sandbox binary config is not sent on restore: the snapshot is
	// self-describing. atelet reads the snapshot manifest to recover the pinned
	// sandbox version that created it.
	Spec *WorkloadSpec  `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type CheckpointType `protobuf:"varint,8,opt,name=type,proto3,enum=atelet.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*RestoreRequest_LocalConfig
	//	*RestoreRequest_ExternalConfig
	Config isRestoreRequest_Config `protobuf_oneof:"config"`
	// What content to restore from the checkpoint.
	Scope SnapshotScope `protobuf:"varint,11,opt,name=scope,proto3,enum=atelet.SnapshotScope" json:"scope,omitempty"`
	// The object storage URI prefix of the ActorTemplate's golden snapshot.
	// Set only when scope is SNAPSHOT_SCOPE_DATA_ON_GOLDEN: restore combines
	// the golden snapshot (memory + full fs delta) with the durable data in
	// the snapshot referenced by `config`. A top-level field rather than part
	// of the `config` oneof: the actor's snapshot may be local (a pause
	// checkpoint) while the golden snapshot is always external.
	GoldenSnapshotUriPrefix string `protobuf:"bytes,12,opt,name=golden_snapshot_uri_prefix,json=goldenSnapshotUriPrefix,proto3" json:"golden_snapshot_uri_prefix,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_atelet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *RestoreRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *RestoreRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RestoreRequest) GetActorUid() string {
	if x != nil {
		return x.ActorUid
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RestoreRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestoreRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *RestoreRequest) GetConfig() isRestoreRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RestoreRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *RestoreRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

func (x *RestoreRequest) GetScope() SnapshotScope {
	if x != nil {
		return x.Scope
	}
	return SnapshotScope_SNAPSHOT_SCOPE_UNSPECIFIED
}

func (x *RestoreRequest) GetGoldenSnapshotUriPrefix() string {
	if x != nil {
		return x.GoldenSnapshotUriPrefix
	}
	return ""
}

type isRestoreRequest_Config interface {
	isRestoreRequest_Config()
}

type RestoreRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,9,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type RestoreRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,10,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*RestoreRequest_LocalConfig) isRestoreRequest_Config() {}

func (*RestoreRequest_ExternalConfig) isRestoreRequest_Config() {}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_atelet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{19}
}

var File_atelet_proto protoreflect.FileDescriptor

const file_atelet_proto_rawDesc = "" +
	"\n" +
	"\fatelet.proto\x12\x06atelet\"\xe0\x02\n" +
	"\n" +
	"RunRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x03 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x04 \x01(\tR\bactorUid\x128\n" +
	"\x18actor_template_namespace\x18\x05 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x06 \x01(\tR\x11actorTemplateName\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\x12<\n" +
	"\x0esandbox_assets\x18\b \x01(\v2\x15.atelet.SandboxAssetsR\rsandboxAssets\"5\n" +
	"\tAssetFile\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x8e\x01\n" +
	"\n" +
	"ArchAssets\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.atelet.ArchAssets.FilesEntryR\x05files\x1aK\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.atelet.AssetFileR\x05value:\x028\x01\"\xbe\x01\n" +
	"\rSandboxAssets\x12#\n" +
	"\rsandbox_class\x18\x01 \x01(\tR\fsandboxClass\x129\n" +
	"\x06assets\x18\x02 \x03(\v2!.atelet.SandboxAssets.AssetsEntryR\x06assets\x1aM\n" +
	"\vAssetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.atelet.ArchAssetsR\x05value:\x028\x01\"\x8c\x01\n" +
	"\fWorkloadSpec\x121\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x11.atelet.ContainerR\n" +
	"containers\x12\x1f\n" +
	"\vpause_image\x18\x02 \x01(\tR\n" +
	"pauseImage\x12(\n" +
	"\avolumes\x18\x03 \x03(\v2\x0e.atelet.VolumeR\avolumes\"\x12\n" +
	"\x10DurableDirVolume\"c\n" +
	"\x14ExternalVolumeSource\x12*\n" +
	"\x11storage_volume_id\x18\x01 \x01(\tR\x0fstorageVolumeId\x12\x1f\n" +
	"\vvolume_type\x18\x02 \x01(\tR\n" +
	"volumeType\"\xc7\x01\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.atelet.VolumeTypeR\x04type\x12;\n" +
	"\vdurable_dir\x18\x03 \x01(\v2\x18.atelet.DurableDirVolumeH\x00R\n" +
	"durableDir\x12:\n" +
	"\bexternal\x18\x04 \x01(\v2\x1c.atelet.ExternalVolumeSourceH\x00R\bexternalB\b\n" +
	"\x06source\"@\n" +
	"\vVolumeMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\"\xe9\x01\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x12\"\n" +
	"\x03env\x18\x04 \x03(\v2\x10.atelet.EnvEntryR\x03env\x12&\n" +
	"\x06readyz\x18\x05 \x01(\v2\x0e.atelet.ReadyzR\x06readyz\x128\n" +
	"\rvolume_mounts\x18\x06 \x03(\v2\x13.atelet.VolumeMountR\fvolumeMounts\"4\n" +
	"\bEnvEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"c\n" +
	"\x06Readyz\x120\n" +
	"\bhttp_get\x18\x01 \x01(\v2\x15.atelet.HTTPGetActionR\ahttpGet\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"7\n" +
	"\rHTTPGetAction\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\r\n" +
	"\vRunResponse\"G\n" +
	"\x1cLocalCheckpointConfiguration\x12'\n" +
	"\x0fsnapshot_prefix\x18\x01 \x01(\tR\x0esnapshotPrefix\"Q\n" +
	"\x1fExternalCheckpointConfiguration\x12.\n" +
	"\x13snapshot_uri_prefix\x18\x01 \x01(\tR\x11snapshotUriPrefix\"\xab\x04\n" +
	"\x11CheckpointRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x03 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x04 \x01(\tR\bactorUid\x128\n" +
	"\x18actor_template_namespace\x18\x05 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x06 \x01(\tR\x11actorTemplateName\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\x12*\n" +
	"\x04type\x18\b \x01(\x0e2\x16.atelet.CheckpointTypeR\x04type\x12I\n" +
	"\flocal_config\x18\t \x01(\v2$.atelet.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12R\n" +
	"\x0fexternal_config\x18\n" +
	" \x01(\v2'.atelet.ExternalCheckpointConfigurationH\x00R\x0eexternalConfig\x12+\n" +
	"\x05scope\x18\v \x01(\x0e2\x15.atelet.SnapshotScopeR\x05scopeB\b\n" +
	"\x06config\"\x14\n" +
	"\x12CheckpointResponse\"\xe5\x04\n" +
	"\x0eRestoreRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x03 \x01(\tR\tactorName\x12\x1b\n" +
	"\tactor_uid\x18\x04 \x01(\tR\bactorUid\x128\n" +
	"\x18actor_template_namespace\x18\x05 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x06 \x01(\tR\x11actorTemplateName\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\x12*\n" +
	"\x04type\x18\b \x01(\x0e2\x16.atelet.CheckpointTypeR\x04type\x12I\n" +
	"\flocal_config\x18\t \x01(\v2$.atelet.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12R\n" +
	"\x0fexternal_config\x18\n" +
	" \x01(\v2'.atelet.ExternalCheckpointConfigurationH\x00R\x0eexternalConfig\x12+\n" +
	"\x05scope\x18\v \x01(\x0e2\x15.atelet.SnapshotScopeR\x05scope\x12;\n" +
	"\x1agolden_snapshot_uri_prefix\x18\f \x01(\tR\x17goldenSnapshotUriPrefixB\b\n" +
	"\x06config\"\x11\n" +
	"\x0fRestoreResponse*`\n" +
	"\n" +
	"VolumeType\x12\x1b\n" +
	"\x17VOLUME_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VOLUME_TYPE_DURABLE_DIR\x10\x01\x12\x18\n" +
	"\x14VOLUME_TYPE_EXTERNAL\x10\x02*j\n" +
	"\x0eCheckpointType\x12\x1f\n" +
	"\x1bCHECKPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHECKPOINT_TYPE_LOCAL\x10\x01\x12\x1c\n" +
	"\x18CHECKPOINT_TYPE_EXTERNAL\x10\x02*\x84\x01\n" +
	"\rSnapshotScope\x12\x1e\n" +
	"\x1aSNAPSHOT_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_FULL\x10\x01\x12\x17\n" +
	"\x13SNAPSHOT_SCOPE_DATA\x10\x02\x12!\n" +
	"\x1dSNAPSHOT_SCOPE_DATA_ON_GOLDEN\x10\x032\xc4\x01\n" +
	"\vAteomHerder\x120\n" +
	"\x03Run\x12\x12.atelet.RunRequest\x1a\x13.atelet.RunResponse\"\x00\x12E\n" +
	"\n" +
	"Checkpoint\x12\x19.atelet.CheckpointRequest\x1a\x1a.atelet.CheckpointResponse\"\x00\x12<\n" +
	"\aRestore\x12\x16.atelet.RestoreRequest\x1a\x17.atelet.RestoreResponse\"\x00B>Z<github.com/agent-substrate/substrate/internal/proto/ateletpbb\x06proto3"

var (
	file_atelet_proto_rawDescOnce sync.Once
	file_atelet_proto_rawDescData []byte
)

func file_atelet_proto_rawDescGZIP() []byte {
	file_atelet_proto_rawDescOnce.Do(func() {
		file_atelet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atelet_proto_rawDesc), len(file_atelet_proto_rawDesc)))
	})
	return file_atelet_proto_rawDescData
}

var file_atelet_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_atelet_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_atelet_proto_goTypes = []any{
	(VolumeType)(0),                         // 0: atelet.VolumeType
	(CheckpointType)(0),                     // 1: atelet.CheckpointType
	(SnapshotScope)(0),                      // 2: atelet.SnapshotScope
	(*RunRequest)(nil),                      // 3: atelet.RunRequest
	(*AssetFile)(nil),                       // 4: atelet.AssetFile
	(*ArchAssets)(nil),                      // 5: atelet.ArchAssets
	(*SandboxAssets)(nil),                   // 6: atelet.SandboxAssets
	(*WorkloadSpec)(nil),                    // 7: atelet.WorkloadSpec
	(*DurableDirVolume)(nil),                // 8: atelet.DurableDirVolume
	(*ExternalVolumeSource)(nil),            // 9: atelet.ExternalVolumeSource
	(*Volume)(nil),                          // 10: atelet.Volume
	(*VolumeMount)(nil),                     // 11: atelet.VolumeMount
	(*Container)(nil),                       // 12: atelet.Container
	(*EnvEntry)(nil),                        // 13: atelet.EnvEntry
	(*Readyz)(nil),                          // 14: atelet.Readyz
	(*HTTPGetAction)(nil),                   // 15: atelet.HTTPGetAction
	(*RunResponse)(nil),                     // 16: atelet.RunResponse
	(*LocalCheckpointConfiguration)(nil),    // 17: atelet.LocalCheckpointConfiguration
	(*ExternalCheckpointConfiguration)(nil), // 18: atelet.ExternalCheckpointConfiguration
	(*CheckpointRequest)(nil),               // 19: atelet.CheckpointRequest
	(*CheckpointResponse)(nil),              // 20: atelet.CheckpointResponse
	(*RestoreRequest)(nil),                  // 21: atelet.RestoreRequest
	(*RestoreResponse)(nil),                 // 22: atelet.RestoreResponse
	nil,                                     // 23: atelet.ArchAssets.FilesEntry
	nil,                                     // 24: atelet.SandboxAssets.AssetsEntry
}
var file_atelet_proto_depIdxs = []int32{
	7,  // 0: atelet.RunRequest.spec:type_name -> atelet.WorkloadSpec
	6,  // 1: atelet.RunRequest.sandbox_assets:type_name -> atelet.SandboxAssets
	23, // 2: atelet.ArchAssets.files:type_name -> atelet.ArchAssets.FilesEntry
	24, // 3: atelet.SandboxAssets.assets:type_name -> atelet.SandboxAssets.AssetsEntry
	12, // 4: atelet.WorkloadSpec.containers:type_name -> atelet.Container
	10, // 5: atelet.WorkloadSpec.volumes:type_name -> atelet.Volume
	0,  // 6: atelet.Volume.type:type_name -> atelet.VolumeType
	8,  // 7: atelet.Volume.durable_dir:type_name -> atelet.DurableDirVolume
	9,  // 8: atelet.Volume.external:type_name -> atelet.ExternalVolumeSource
	13, // 9: atelet.Container.env:type_name -> atelet.EnvEntry
	14, // 10: atelet.Container.readyz:type_name -> atelet.Readyz
	11, // 11: atelet.Container.volume_mounts:type_name -> atelet.VolumeMount
	15, // 12: atelet.Readyz.http_get:type_name -> atelet.HTTPGetAction
	7,  // 13: atelet.CheckpointRequest.spec:type_name -> atelet.WorkloadSpec
	1,  // 14: atelet.CheckpointRequest.type:type_name -> atelet.CheckpointType
	17, // 15: atelet.CheckpointRequest.local_config:type_name -> atelet.LocalCheckpointConfiguration
	18, // 16: atelet.CheckpointRequest.external_config:type_name -> atelet.ExternalCheckpointConfiguration
	2,  // 17: atelet.CheckpointRequest.scope:type_name -> atelet.SnapshotScope
	7,  // 18: atelet.RestoreRequest.spec:type_name -> atelet.WorkloadSpec
	1,  // 19: atelet.RestoreRequest.type:type_name -> atelet.CheckpointType
	17, // 20: atelet.RestoreRequest.local_config:type_name -> atelet.LocalCheckpointConfiguration
	18, // 21: atelet.RestoreRequest.external_config:type_name -> atelet.ExternalCheckpointConfiguration
	2,  // 22: atelet.RestoreRequest.scope:type_name -> atelet.SnapshotScope
	4,  // 23: atelet.ArchAssets.FilesEntry.value:type_name -> atelet.AssetFile
	5,  // 24: atelet.SandboxAssets.AssetsEntry.value:type_name -> atelet.ArchAssets
	3,  // 25: atelet.AteomHerder.Run:input_type -> atelet.RunRequest
	19, // 26: atelet.AteomHerder.Checkpoint:input_type -> atelet.CheckpointRequest
	21, // 27: atelet.AteomHerder.Restore:input_type -> atelet.RestoreRequest
	16, // 28: atelet.AteomHerder.Run:output_type -> atelet.RunResponse
	20, // 29: atelet.AteomHerder.Checkpoint:output_type -> atelet.CheckpointResponse
	22, // 30: atelet.AteomHerder.Restore:output_type -> atelet.RestoreResponse
	28, // [28:31] is the sub-list for method output_type
	25, // [25:28] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_atelet_proto_init() }
func file_atelet_proto_init() {
	if File_atelet_proto != nil {
		return
	}
	file_atelet_proto_msgTypes[7].OneofWrappers = []any{
		(*Volume_DurableDir)(nil),
		(*Volume_External)(nil),
	}
	file_atelet_proto_msgTypes[16].OneofWrappers = []any{
		(*CheckpointRequest_LocalConfig)(nil),
		(*CheckpointRequest_ExternalConfig)(nil),
	}
	file_atelet_proto_msgTypes[18].OneofWrappers = []any{
		(*RestoreRequest_LocalConfig)(nil),
		(*RestoreRequest_ExternalConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atelet_proto_rawDesc), len(file_atelet_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atelet_proto_goTypes,
		DependencyIndexes: file_atelet_proto_depIdxs,
		EnumInfos:         file_atelet_proto_enumTypes,
		MessageInfos:      file_atelet_proto_msgTypes,
	}.Build()
	File_atelet_proto = out.File
	file_atelet_proto_goTypes = nil
	file_atelet_proto_depIdxs = nil
}
