// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: atelet.proto

package ateletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AteomSupport_MintActorCertificate_FullMethodName = "/atelet.AteomSupport/MintActorCertificate"
	AteomSupport_SetWorkerCapacity_FullMethodName    = "/atelet.AteomSupport/SetWorkerCapacity"
)

// AteomSupportClient is the client API for AteomSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AteomSupport provides callouts for ateom.
//
// Called by individual ateom pods over a local connection, authenticated with
// ateom's k8s pod identity mTLS certificate.
type AteomSupportClient interface {
	// Request an atunnel certificate for the given actor.
	//
	// TODO(identity): Rename to MintAtunnelCertificate, as distinct from
	// MintActorCertificate (which would be used for certificates projected into
	// the actor filesystem, when/if we support those).
	MintActorCertificate(ctx context.Context, in *MintActorCertificateRequest, opts ...grpc.CallOption) (*MintActorCertificateResponse, error)
	// Report capacity and supply for this worker back to atelet.
	SetWorkerCapacity(ctx context.Context, in *SetWorkerCapacityRequest, opts ...grpc.CallOption) (*SetWorkerCapacityResponse, error)
}

type ateomSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewAteomSupportClient(cc grpc.ClientConnInterface) AteomSupportClient {
	return &ateomSupportClient{cc}
}

func (c *ateomSupportClient) MintActorCertificate(ctx context.Context, in *MintActorCertificateRequest, opts ...grpc.CallOption) (*MintActorCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintActorCertificateResponse)
	err := c.cc.Invoke(ctx, AteomSupport_MintActorCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomSupportClient) SetWorkerCapacity(ctx context.Context, in *SetWorkerCapacityRequest, opts ...grpc.CallOption) (*SetWorkerCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWorkerCapacityResponse)
	err := c.cc.Invoke(ctx, AteomSupport_SetWorkerCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteomSupportServer is the server API for AteomSupport service.
// All implementations must embed UnimplementedAteomSupportServer
// for forward compatibility.
//
// AteomSupport provides callouts for ateom.
//
// Called by individual ateom pods over a local connection, authenticated with
// ateom's k8s pod identity mTLS certificate.
type AteomSupportServer interface {
	// Request an atunnel certificate for the given actor.
	//
	// TODO(identity): Rename to MintAtunnelCertificate, as distinct from
	// MintActorCertificate (which would be used for certificates projected into
	// the actor filesystem, when/if we support those).
	MintActorCertificate(context.Context, *MintActorCertificateRequest) (*MintActorCertificateResponse, error)
	// Report capacity and supply for this worker back to atelet.
	SetWorkerCapacity(context.Context, *SetWorkerCapacityRequest) (*SetWorkerCapacityResponse, error)
	mustEmbedUnimplementedAteomSupportServer()
}

// UnimplementedAteomSupportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAteomSupportServer struct{}

func (UnimplementedAteomSupportServer) MintActorCertificate(context.Context, *MintActorCertificateRequest) (*MintActorCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintActorCertificate not implemented")
}
func (UnimplementedAteomSupportServer) SetWorkerCapacity(context.Context, *SetWorkerCapacityRequest) (*SetWorkerCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWorkerCapacity not implemented")
}
func (UnimplementedAteomSupportServer) mustEmbedUnimplementedAteomSupportServer() {}
func (UnimplementedAteomSupportServer) testEmbeddedByValue()                      {}

// UnsafeAteomSupportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AteomSupportServer will
// result in compilation errors.
type UnsafeAteomSupportServer interface {
	mustEmbedUnimplementedAteomSupportServer()
}

func RegisterAteomSupportServer(s grpc.ServiceRegistrar, srv AteomSupportServer) {
	// If the following call panics, it indicates UnimplementedAteomSupportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AteomSupport_ServiceDesc, srv)
}

func _AteomSupport_MintActorCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintActorCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomSupportServer).MintActorCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomSupport_MintActorCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomSupportServer).MintActorCertificate(ctx, req.(*MintActorCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteomSupport_SetWorkerCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWorkerCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomSupportServer).SetWorkerCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomSupport_SetWorkerCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomSupportServer).SetWorkerCapacity(ctx, req.(*SetWorkerCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AteomSupport_ServiceDesc is the grpc.ServiceDesc for AteomSupport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AteomSupport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atelet.AteomSupport",
	HandlerType: (*AteomSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintActorCertificate",
			Handler:    _AteomSupport_MintActorCertificate_Handler,
		},
		{
			MethodName: "SetWorkerCapacity",
			Handler:    _AteomSupport_SetWorkerCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atelet.proto",
}

const (
	AteomHerder_Run_FullMethodName                    = "/atelet.AteomHerder/Run"
	AteomHerder_Checkpoint_FullMethodName             = "/atelet.AteomHerder/Checkpoint"
	AteomHerder_Restore_FullMethodName                = "/atelet.AteomHerder/Restore"
	AteomHerder_UploadPausedCheckpoint_FullMethodName = "/atelet.AteomHerder/UploadPausedCheckpoint"
	AteomHerder_Terminate_FullMethodName              = "/atelet.AteomHerder/Terminate"
)

// AteomHerderClient is the client API for AteomHerder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AteomHerder allows ate-apiserver to issue control calls to the atelet.
//
// Called by ate-api-server over cluster networking.  ate-api-server
// authenticates with its k8s pod identity mTLS certificate.
type AteomHerderClient interface {
	// Run tells atelet to create a new containerized workload from scratch on an
	// ateom.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	// Checkpoint tells atelet to save the current state of the workload on an
	// ateom to object storage, and then completely the ateom to a blank state
	// (back to "available" state.)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// Restore restores a workload from checkpoint onto an ateom.
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// UploadPausedCheckpoint copies a local (pause) checkpoint from this node's
	// disk to object storage. Unlike Checkpoint it drives no ateom: the actor is
	// paused, its sandbox is gone; the checkpoint files plus their manifest
	// already sit under the actor's local-checkpoints directory.
	UploadPausedCheckpoint(ctx context.Context, in *UploadPausedCheckpointRequest, opts ...grpc.CallOption) (*UploadPausedCheckpointResponse, error)
	// Terminate tells atelet to terminate/kill any running workload for an actor,
	// unmount its volumes, and clean up actor state on the node.
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type ateomHerderClient struct {
	cc grpc.ClientConnInterface
}

func NewAteomHerderClient(cc grpc.ClientConnInterface) AteomHerderClient {
	return &ateomHerderClient{cc}
}

func (c *ateomHerderClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, AteomHerder_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomHerderClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, AteomHerder_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomHerderClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, AteomHerder_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomHerderClient) UploadPausedCheckpoint(ctx context.Context, in *UploadPausedCheckpointRequest, opts ...grpc.CallOption) (*UploadPausedCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPausedCheckpointResponse)
	err := c.cc.Invoke(ctx, AteomHerder_UploadPausedCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateomHerderClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, AteomHerder_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteomHerderServer is the server API for AteomHerder service.
// All implementations must embed UnimplementedAteomHerderServer
// for forward compatibility.
//
// AteomHerder allows ate-apiserver to issue control calls to the atelet.
//
// Called by ate-api-server over cluster networking.  ate-api-server
// authenticates with its k8s pod identity mTLS certificate.
type AteomHerderServer interface {
	// Run tells atelet to create a new containerized workload from scratch on an
	// ateom.
	Run(context.Context, *RunRequest) (*RunResponse, error)
	// Checkpoint tells atelet to save the current state of the workload on an
	// ateom to object storage, and then completely the ateom to a blank state
	// (back to "available" state.)
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// Restore restores a workload from checkpoint onto an ateom.
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// UploadPausedCheckpoint copies a local (pause) checkpoint from this node's
	// disk to object storage. Unlike Checkpoint it drives no ateom: the actor is
	// paused, its sandbox is gone; the checkpoint files plus their manifest
	// already sit under the actor's local-checkpoints directory.
	UploadPausedCheckpoint(context.Context, *UploadPausedCheckpointRequest) (*UploadPausedCheckpointResponse, error)
	// Terminate tells atelet to terminate/kill any running workload for an actor,
	// unmount its volumes, and clean up actor state on the node.
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedAteomHerderServer()
}

// UnimplementedAteomHerderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAteomHerderServer struct{}

func (UnimplementedAteomHerderServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAteomHerderServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedAteomHerderServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedAteomHerderServer) UploadPausedCheckpoint(context.Context, *UploadPausedCheckpointRequest) (*UploadPausedCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPausedCheckpoint not implemented")
}
func (UnimplementedAteomHerderServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedAteomHerderServer) mustEmbedUnimplementedAteomHerderServer() {}
func (UnimplementedAteomHerderServer) testEmbeddedByValue()                     {}

// UnsafeAteomHerderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AteomHerderServer will
// result in compilation errors.
type UnsafeAteomHerderServer interface {
	mustEmbedUnimplementedAteomHerderServer()
}

func RegisterAteomHerderServer(s grpc.ServiceRegistrar, srv AteomHerderServer) {
	// If the following call panics, it indicates UnimplementedAteomHerderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AteomHerder_ServiceDesc, srv)
}

func _AteomHerder_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomHerderServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomHerder_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomHerderServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteomHerder_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomHerderServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomHerder_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomHerderServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteomHerder_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomHerderServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomHerder_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomHerderServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteomHerder_UploadPausedCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPausedCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomHerderServer).UploadPausedCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomHerder_UploadPausedCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomHerderServer).UploadPausedCheckpoint(ctx, req.(*UploadPausedCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteomHerder_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteomHerderServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AteomHerder_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteomHerderServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AteomHerder_ServiceDesc is the grpc.ServiceDesc for AteomHerder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AteomHerder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atelet.AteomHerder",
	HandlerType: (*AteomHerderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _AteomHerder_Run_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _AteomHerder_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _AteomHerder_Restore_Handler,
		},
		{
			MethodName: "UploadPausedCheckpoint",
			Handler:    _AteomHerder_UploadPausedCheckpoint_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _AteomHerder_Terminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atelet.proto",
}
