# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: ate-demo-counter-microvm-csi

---

apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  name: counter-microvm-csi
  namespace: ate-demo-counter-microvm-csi
  labels:
    workload: counter-microvm-csi
spec:
  replicas: 1
  sandboxClass: microvm
  sandboxConfigName: microvm
  ateomImage: ko://github.com/agent-substrate/substrate/cmd/ateom-microvm

---

apiVersion: ate.dev/v1alpha1
kind: ActorTemplate
metadata:
  name: counter-microvm-csi
  namespace: ate-demo-counter-microvm-csi
spec:
  sandboxClass: microvm
  containers:
  - name: counter
    image: ko://github.com/agent-substrate/substrate/demos/counter
    readyz:
      httpGet:
        path: /readyz
        port: 80
    volumeMounts:
    - name: data
      mountPath: /home/counter
  workerSelector:
    matchLabels:
      workload: counter-microvm-csi
  snapshotsConfig:
    onPause: Full
    onCommit: Data
    onResume:
      fromData: Golden
    location: gs://ate-snapshots/ate-demo-counter-microvm-csi/
  volumes:
  - name: data
    externalVolumeTemplate:
      capacity: 1Gi
      storageClassName: csi-hostpath-sc
