// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	pkgapiv1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	versioned "github.com/agent-substrate/substrate/pkg/client/clientset/versioned"
	internalinterfaces "github.com/agent-substrate/substrate/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CSIDriverConfigInformer provides access to a shared informer and lister for
// CSIDriverConfigs. Prefer using the type-safe variant (see [TypedCSIDriverConfigInformer]).
type CSIDriverConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.CSIDriverConfigLister
}

// TypedCSIDriverConfigInformer provides access to a shared informer and lister for
// CSIDriverConfigs, including the type-safe TypedInformer variant.
// It is a superset of CSIDriverConfigInformer.
type TypedCSIDriverConfigInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CSIDriverConfigIndexInformer
	Lister() apiv1alpha1.CSIDriverConfigLister
}

// CSIDriverConfigIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CSIDriverConfigIndexInformer cache.TypedSharedIndexInformer[*pkgapiv1alpha1.CSIDriverConfig]

// CSIDriverConfigHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for CSIDriverConfig.
type CSIDriverConfigHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*pkgapiv1alpha1.CSIDriverConfig]

// CSIDriverConfigDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for CSIDriverConfig.
type CSIDriverConfigDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*pkgapiv1alpha1.CSIDriverConfig]

// CSIDriverConfigFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for CSIDriverConfig.
type CSIDriverConfigFilteringHandler = cache.TypedFilteringResourceEventHandler[*pkgapiv1alpha1.CSIDriverConfig]

// CSIDriverConfigIndexers is a specialization of [cache.TypedIndexers] for CSIDriverConfig.
type CSIDriverConfigIndexers = cache.TypedIndexers[*pkgapiv1alpha1.CSIDriverConfig]

// DeletedCSIDriverConfig is a specialization of [cache.DeletedObject] for CSIDriverConfig.
type DeletedCSIDriverConfig = cache.DeletedObject[*pkgapiv1alpha1.CSIDriverConfig]

type cSIDriverConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCSIDriverConfigInformer constructs a new informer for CSIDriverConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCSIDriverConfigInformer]).
func NewCSIDriverConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCSIDriverConfigInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCSIDriverConfigInformer constructs a new informer for CSIDriverConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCSIDriverConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CSIDriverConfigIndexers) CSIDriverConfigIndexInformer {
	return NewTypedCSIDriverConfigInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCSIDriverConfigInformer constructs a new informer for CSIDriverConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCSIDriverConfigInformer]).
func NewFilteredCSIDriverConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCSIDriverConfigInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCSIDriverConfigInformer constructs a new informer for CSIDriverConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCSIDriverConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CSIDriverConfigIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CSIDriverConfigIndexInformer {
	return NewTypedCSIDriverConfigInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCSIDriverConfigInformerWithOptions constructs a new informer for CSIDriverConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCSIDriverConfigInformerWithOptions]).
func NewCSIDriverConfigInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCSIDriverConfigInformerWithOptions(client, options)
}

// NewTypedCSIDriverConfigInformerWithOptions constructs a new informer for CSIDriverConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCSIDriverConfigInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) CSIDriverConfigIndexInformer {
	gvr := schema.GroupVersionResource{Group: "api", Version: "v1alpha1", Resource: "csidriverconfigs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*pkgapiv1alpha1.CSIDriverConfig](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiV1alpha1().CSIDriverConfigs().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiV1alpha1().CSIDriverConfigs().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiV1alpha1().CSIDriverConfigs().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ApiV1alpha1().CSIDriverConfigs().Watch(ctx, opts)
			},
		}, client),
		&pkgapiv1alpha1.CSIDriverConfig{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *cSIDriverConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCSIDriverConfigInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *cSIDriverConfigInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *cSIDriverConfigInformer) TypedInformer() CSIDriverConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*pkgapiv1alpha1.CSIDriverConfig](f.factory.InformerFor(&pkgapiv1alpha1.CSIDriverConfig{}, f.defaultInformer))
}

func (f *cSIDriverConfigInformer) Lister() apiv1alpha1.CSIDriverConfigLister {
	return apiv1alpha1.NewCSIDriverConfigLister(f.Informer().GetIndexer())
}

// ToTypedCSIDriverConfigInformer converts an untyped informer into a TypedCSIDriverConfigInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CSIDriverConfig. If that is not the case, calling type-safe methods of the returned
// TypedCSIDriverConfigInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCSIDriverConfigInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCSIDriverConfigInformer(informer CSIDriverConfigInformer) TypedCSIDriverConfigInformer {
	if informer, ok := informer.(TypedCSIDriverConfigInformer); ok {
		return informer
	}
	return &cSIDriverConfigTypedInformerAdapter{informer}
}

type cSIDriverConfigTypedInformerAdapter struct {
	CSIDriverConfigInformer
}

func (a *cSIDriverConfigTypedInformerAdapter) TypedInformer() CSIDriverConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*pkgapiv1alpha1.CSIDriverConfig](a.Informer())
}

// ToCSIDriverConfigIndexInformer converts an untyped informer into a CSIDriverConfigIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CSIDriverConfig. If that is not the case, calling type-safe methods of the returned
// CSIDriverConfigIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CSIDriverConfigIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCSIDriverConfigIndexInformer(informer cache.SharedIndexInformer) CSIDriverConfigIndexInformer {
	if informer, ok := informer.(CSIDriverConfigIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*pkgapiv1alpha1.CSIDriverConfig](informer)
}
