#!/usr/bin/env bash

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Regenerate the vendored kubernetes-sigs/nat64 manifest from the pin in
# hack/third_party/nat64/VERSION. Re-running this on an unchanged pin must
# produce no diff, so `git diff --exit-code` after it is a drift check.

set -o errexit -o nounset -o pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "${ROOT}"

DIR="hack/third_party/nat64"

# shellcheck source=../third_party/nat64/VERSION
source "${DIR}/VERSION"

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

curl -fsSL --retry 3 \
  "https://raw.githubusercontent.com/kubernetes-sigs/nat64/${NAT64_COMMIT}/install.yaml" \
  -o "${tmp}"

# Refuse to emit a manifest whose image we did not actually pin: if upstream
# renames the image or grows a second container, the substitution below would
# silently leave an unpinned tag in the output.
found="$(grep -c '^ *image: registry\.k8s\.io/networking/nat64:' "${tmp}" || true)"
if [[ "${found}" != 1 ]]; then
  echo "expected exactly one nat64 image line upstream, found ${found}" >&2
  exit 1
fi

{
  cat <<EOF
# Generated by hack/update/nat64.sh -- DO NOT EDIT.
#
# kubernetes-sigs/nat64, copied verbatim from
# https://github.com/kubernetes-sigs/nat64/blob/${NAT64_COMMIT}/install.yaml
# with the agent image pinned by digest. Apache-2.0; see LICENSE.
#
# README.md covers the pin and how to regenerate this; docs/dev/ipv6-local.md
# covers using it.
EOF
  sed -e "s|^\( *image: \)registry\.k8s\.io/networking/nat64:.*|\1${NAT64_IMAGE}|" "${tmp}"
} >"${DIR}/install.yaml"

echo "Wrote ${DIR}/install.yaml from ${NAT64_COMMIT}"
